### ISSUE TITLE
Icon request: icon-mongodb

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#102]
MongoDB is a NoSQL language and possibly the most popular one, used in MEAN, MERN, MEN, ... stacks for the web, it's also good to have when listing skills as FA icons and for stacks description.

![MongoDB](https://upload.wikimedia.org/wikipedia/en/thumb/4/45/MongoDB-Logo.svg/250px-MongoDB-Logo.svg.png)

**Comment by xuv** [comment]
Thanks for the suggestion. Although I have not found a mono-color version of the logo and the [MongoDB brand resource page](https://www.mongodb.com/brand-resources) explicitly says they don't want anyone changing those colors. So I don't think this logo should be added.

**Comment by Berkmann18** [comment]
Oh well.
