### ISSUE TITLE
Icon request: icon-photoshop

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#104]
It would amazing if there was an icon for photoshop.

![Ps](https://images.ecosia.org/uDml7DE7fT6WIOgCzgPAB-6qj1Q=/0x390/smart/https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F9%2F92%2FAdobe_Photoshop_CS6_icon.svg%2F1041px-Adobe_Photoshop_CS6_icon.svg.png)

**Comment by xuv** [comment]
We should probably split this issue into 2 for easier tracking...

**Comment by Berkmann18** [comment]
Sure.

**Comment by xuv** [comment]
Actually, after reading Adobe requirements, I would prefer not to go forward with this request:
> Adobe does not allow the use of its product icons by third parties in their products or related materials of any kind, except through an Adobe partnership agreement.

Source: https://www.adobe.com/legal/permissions/icons-web-logos.html#icons

There is no point for us to get in trouble with Adobe.
