### ISSUE TITLE
Icon Request: fa-gitea

### ISSUE THREAD

**Issue by Ceda-EI** [ForkAwesome/Fork-Awesome#107]
[Gitea](https://gitea.io/) is a community managed fork of Gogs, lightweight code hosting solution written in Go and published under the MIT license. 

[They have an svg logo here](https://github.com/go-gitea/gitea/blob/master/assets/logo.svg)

**Comment by xuv** [comment]
Thx for the suggestion.

**Comment by Ceda-EI** [comment]
Here is an svg. I would send a PR instead but font forge is having some issues. :)
[logo.zip](https://github.com/ForkAwesome/Fork-Awesome/files/2345057/logo.zip)

**Comment by Ceda-EI** [comment]
PNG Preview
![logo](https://user-images.githubusercontent.com/19731116/44980121-92531200-af8c-11e8-9365-4f2164e00daf.png)

**Comment by xuv** [comment]
@tessus No prob. I'll assign this issue to me then.
