### ISSUE TITLE
Icon Request: fa-versions

### ISSUE THREAD

**Issue by Petrouchka** [ForkAwesome/Fork-Awesome#110]
I'd like to have an icon for menu in Wiki, to show the different versions of a page and to revert to an old version (an icon "hystory" or "versions"). Something like this :
![icon-versions](https://user-images.githubusercontent.com/3955499/44944996-e15c4400-ade0-11e8-84d9-7c060c654e9a.png)

**Comment by FramaJosephK** [comment]
It already exists https://forkawesome.github.io/Fork-Awesome/icon/history/

**Comment by Petrouchka** [comment]
Ooh, I looked at it several times and did not find it. thank you very much.

**Comment by Petrouchka** [comment]
Ooh, I looked at it several times and did not find it. thank you very much.
