### ISSUE TITLE
Icon request: fa-classicpress

### ISSUE THREAD

**Issue by ginsterbusch** [ForkAwesome/Fork-Awesome#111]
ClassicPress is a fork of WordPress, without Gutenberg.

To quote straight from the [home page](http://www.classicpress.net):

> Meet ClassicPress
> The WordPress you know and love, without Gutenberg (and an exciting future!)
> Version 1 of ClassicPress will be a Gutenberg free experience of WordPress, compatible with your 
> existing site.

**Comment by xxsimoxx** [comment]
To help here there is the official logo.

**Example image**
the example images are the SVG original logo.
 ![negative logo SVG](https://docs.classicpress.net/wp-content/classicpress/logos/feather-white.svg)
 ![negative logo in circle SVG](https://docs.classicpress.net/wp-content/classicpress/logos/icon-gradient.svg)
