### ISSUE TITLE
consider including the full license in the headers

### ISSUE THREAD

**Issue by aviau** [ForkAwesome/Fork-Awesome#113]
People tend to just copy the css files in their open source project, breaking the one single requirement of the MIT license.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Note that even this repository does not contain the license text. Distributing it would break the above requirement.

Maybe it would be a good idea to include the full license in the headers instead of just mentioning the name of the license?

While I am sure that nobody is going to sue anyone, for Debian, this leads to distribution issues. We cannot distribute files that were just copied without respecting the license.

Including the license in the headers prevents this issue.

**Comment by xuv** [comment]
Ok, noted. I will include the licenses in this repo also.

When you mean, include the license in all the headers, you mean the CSS files headers? Or are there other files you think of?

**Comment by aviau** [comment]
I meant the CSS headers, yes!

**Comment by xuv** [comment]
Great thanks.
