### ISSUE TITLE
Icon request: icon-illustrator

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#114]
It would be amazing if there was one for illustrator.

![Ai](https://tse4.mm.bing.net/th?id=OIP.VpQ_yItYnGvADh1oJ8FGwAHaHN&pid=Api)

**Comment by xuv** [comment]
(Same as #104)

After reading Adobe requirements, I would prefer not to go forward with this request:
> Adobe does not allow the use of its product icons by third parties in their products or related materials of any kind, except through an Adobe partnership agreement.

Source: https://www.adobe.com/legal/permissions/icons-web-logos.html#icons

There is no point for us to get in trouble with Adobe.

**Comment by Berkmann18** [comment]
That sucks.
