### ISSUE TITLE
v5 compat: fa-sync is missing

### ISSUE THREAD

**Issue by aviau** [ForkAwesome/Fork-Awesome#115]
Title says it all!

**Comment by xuv** [comment]
Ok, I see that [Font Awesome Sync](https://fontawesome.com/icons/sync?style=solid) is similar to [Fort Awesome Refresh](https://forkawesome.github.io/Fork-Awesome/icon/refresh/). I will add the alias.

**Comment by aviau** [comment]
thanks!
