### ISSUE TITLE
Icon request: fa-python

### ISSUE THREAD

**Issue by andreas-h** [ForkAwesome/Fork-Awesome#124]
Fontawesome now has `fa-python` an icon with the logo of the Python programming language.  It would be great if this could be included here.

[SVG logo](https://www.python.org/static/community_logos/python-logo-generic.svg)

[Python trademark](https://www.python.org/psf/trademarks/)

[Fontawesome `fa-python`](https://fontawesome.com/icons/python?style=brands)

**Comment by Berkmann18** [comment]
+1

**Comment by xuv** [comment]
@Berkmann18 Hey. Really appreciate the enthusiasm here. But Please prefer to use the 👍 reaction to the post (as you already do) than using a `+1` in a comment. Thank you.

**Comment by Berkmann18** [comment]
@xuv Okay.

**Comment by xuv** [comment]
This is fixed in Master. Will be available in the next release.
