### ISSUE TITLE
Icon request: icon-fediverse

### ISSUE THREAD

**Issue by jprojects** [ForkAwesome/Fork-Awesome#125]
We designed a logo proposal that represents the fediverse it would be great the fediverse icon could be included here.

[Wikipedia](https://en.wikipedia.org/wiki/Fediverse)

[SVG color](https://en.wikipedia.org/wiki/Fediverse#/media/File:Fediverse_logo_proposal.svg)

[SVG mono](https://en.wikipedia.org/wiki/Fediverse#/medi/File:Fediverse_logo_proposal_(mono_version).svg)

**Comment by xuv** [comment]
Thanks for the submission and the idea.

If I understand you correctly, you designed this Fediverse logo and you are proposing it for global use.
There is at least another case for a different logo for the fediverse that is available here: https://fediverse.party/

So I would not know which one to use. So I'm thinking of putting this on hold until the Fediverse community adopts this logo or another.

In the meantime, we have logos for [ActivityPub](https://forkawesome.github.io/Fork-Awesome/icon/activitypub/), [GnuSocial](https://forkawesome.github.io/Fork-Awesome/icon/gnu-social/), [Mastodon](https://forkawesome.github.io/Fork-Awesome/icon/mastodon/),... in case people were looking for something similar.

**Comment by salvadorpla** [comment]
My vote goes to [this really nice one](https://en.wikipedia.org/wiki/Fediverse#/media/File:Fediverse_logo_proposal.svg).

**Comment by buttle** [comment]
This represents a diverse network to me. https://en.wikipedia.org/wiki/Fediverse#/media/File:Fediverse_logo_proposal.svg

**Comment by xaloc33** [comment]
I really like the idea behind this one and I think that it represends what the fediverse is.
https://en.wikipedia.org/wiki/Fediverse#/media/File:Fediverse_logo_proposal.svg

**Comment by Zagur** [comment]
I think that this logo (https://en.wikipedia.org/wiki/Fediverse#/media/File:Fediverse_logo_proposal.svg) represents everything that is the fediverse. Community, federation, universe, network, interconnection, freedom...

**Comment by xuv** [comment]
I'd like to inform everyone here that the purpose of this thread is not to discuss a logo proposition for the Fediverse, but whether a logo for the Fediverse should be inserted in the ForkAwesome icon set. 

At this point, the Wikipedia logo you are all referring to is only a logo proposition. Adding +1 or messages here showing your support is not going to change this. What will make this the official logo of the Fediverse is if the Fediverse adopts it as its official logo. So go on the Fediverse (not Github), to do that. Thank you all for your understanding.

**Comment by jprojects** [comment]
Your words: "So I'm thinking of putting this on hold until the Fediverse community adopts this logo or another."

The people who write comments are community, are administrators from nodes that use this logo.

But no problem, you can close the thread because it's impossible to make it official, fediverse it's an abstract entity.

**Comment by xuv** [comment]
@jprojects I have no way to know these people are administrators of nodes. All they point to is your SVG file hosted on Mediawiki. When a group of people will show me a wide adoption of a symbol representing the Fediverse, I will reconsider this demand.

In the meantime, as you suggest, I will close this issue.

**Comment by capiscuas** [comment]
I also vouch for the colorful version of the logo. I even got myself lots of printed stickers to put in my laptop. It is quite broadly adopted.

**Comment by tessus** [comment]
@capiscuas you realize that this font only uses black and white. what are you voting for? the fediverse logo itself? this github project is for the font ForkAwesome.

I'm locking this thread. People apparently do not understand what they are told.
