### ISSUE TITLE
Icon Request: biometric

### ISSUE THREAD

**Issue by tessus** [ForkAwesome/Fork-Awesome#127]
## Icon

![SVG](https://upload.wikimedia.org/wikipedia/commons/f/fb/EPassport_logo.svg)

## Name Suggestion

fa-biometric

## Use Case

This symbol is usually printed on the cover of biometric passports.
It can also be used as a "chip-inside" symbol to denote a product which has a contactless IC embedded that can be used for biometric identification.

**Comment by tessus** [comment]
Community, what do you think? Is this useful? Does an icon like this make sense?

**Comment by Berkmann18** [comment]
It would definitely be useful, especially for websites that would deal with passports or any kind of related documents.

**Comment by xuv** [comment]
@tessus I definitely think you should add this icon to the set. Let me know when you plan to do this.

**Comment by tessus** [comment]
I'll be back home on Saturday. I can work on it then. Most likely I will be able to get to it on Sunday.

**Comment by xuv** [comment]
Cool. No rush. We can program a release for next week then.
