### ISSUE TITLE
Icon request: icon-hackster-io

### ISSUE THREAD

**Issue by vishnumaiea** [ForkAwesome/Fork-Awesome#137]
## Icon

![image](https://user-images.githubusercontent.com/10383395/49821324-358fa080-fda0-11e8-8b00-def2a67fc598.png)

## Name Suggestion

fa-hackster-io

## Use Case

www.hackster.io is a popular maker platform for open source electronics and IoT projects. We could use this icon to link our Hackster profiles.

**Comment by vishnumaiea** [comment]
The blue part could've been ignored. The white part is what important. Or you could add both versions.

![image](https://user-images.githubusercontent.com/10383395/52733160-0851af80-2fe8-11e9-83f0-7f533ac2ab8f.png)

**Comment by xuv** [comment]
According to their branding guidelines, the circle is part of the logo: https://www.hackster.io/branding

**Comment by vishnumaiea** [comment]
Never knew that, because I've seen the logo in multiple colors without the circle. May be they were not following the guidelines.

I've tested the new icon and it works.
