### ISSUE TITLE
Friendica icon bug on mobile browsers

### ISSUE THREAD

**Issue by xuv** [ForkAwesome/Fork-Awesome#14]
The friendica icon displays as a black square on mobile devices.

**Comment by Zatnosk** [comment]
On (windows) desktop too.

**Comment by fabrixxm** [comment]
> macOS: Firefox 58.0.2 works, Chrome 64.0.3282.167 works, safari 11.0.2 works.
> archlinux: firefox 58.0.2 don't works, Gnome Web 3.26.6 don't works

> FF Qantum 58.0.2, Chromium Version 64.0.3282.167, and uzbl stable: looks broken in each [...]  Gentoo, but browsers installed via nix, not via portage.

(from a thread on Friendica)

**Comment by xuv** [comment]
Any idea why that would be the case? I'll try reworking it, but I don't have a lot of devices to test it.

**Comment by rebeka-catalina** [comment]
I have this issue in all my desktop browsers.

**Comment by xuv** [comment]
@rebeka-catalina Could you post the Browser versions and the operating system you are using. Thank you.

**Comment by rebeka-catalina** [comment]
On 2018.02.19, Julien Deswaef wrote:
> @rebeka-catalina Could you post the Browser versions and the operating system you are using. Thank you.

It is what Fabrixxm commented above, Gentoo and browsers installed via
nix. Tested it on NixOS and Slackware64-14.2 with same results, but
now after your changes it works for me in every browser and looks fine :-)

Thank you :-)

**Comment by tobiasd** [comment]
Looks good in Debian Stretch with Vivaldi and Firefox ESR here.

**Comment by fabrixxm** [comment]
Works on Arch Linux, Firefox and GNOME Web :+1:

**Comment by xuv** [comment]
Ok, seems all good now for everyone. Closing issue.

**Comment by tobiasd** [comment]
Thanks for fixing it :-)
