### ISSUE TITLE
Icon Request : icon-unsplash

### ISSUE THREAD

**Issue by thomasbnt** [ForkAwesome/Fork-Awesome#141]
## Icon
![unsplash_symbol_edited](https://user-images.githubusercontent.com/14293805/50018582-18411900-ffd0-11e8-80c9-d3e742db2c3e.png)
[Link to the Official Branding Pack (Dropbox) ](https://www.dropbox.com/sh/ror9hdmwdfl6ajz/AADG179EOuBQZkGri7lzmDbCa/Logo?dl=0&subfolder_nav_tracking=1)

I modified a little to see how it could look like without the shapes and background. Here is the zip with the `.svg` and the `.png` :

[unsplash_symbol_edited_thomasbnt.zip](https://github.com/ForkAwesome/Fork-Awesome/files/2681157/unsplash_symbol_edited_thomasbnt.zip)

## Name Suggestion

unsplash

## Use Case

> Unsplash has grown into an industry-leading photography community. It’s become a source of inspiration for everyone from award-winning writers like Deepak Chopra to industry-titans like Apple, and millions of creators worldwide.

Having Unsplash as an icon would be an advantage for photographers who would like to position links or buttons to their Unsplash profile. Marking with this logo would validate the destination on the Unsplash platform.

Website : https://unsplash.com

**Comment by xuv** [comment]
@thomasbnt In the use case section, you give us the description of Unsplash. What we are looking for here is in what context and how would the users of Fork-Awesome benefit from having an unsplash icon from the set. Thank you.

**Comment by thomasbnt** [comment]
> @thomasbnt In the use case section, you give us the description of Unsplash. What we are looking for here is in what context and how would the users of Fork-Awesome benefit from having an unsplash icon from the set. Thank you.

Edited !
