### ISSUE TITLE
Add GNU icon fa-gnu

### ISSUE THREAD

**Issue by ghost** [ForkAwesome/Fork-Awesome#145]
## Icon

![GNU Logo](https://www.gnu.org/graphics/empowered-by-gnu.svg)

This is a SVG format, so easy to use.

Source file: https://www.gnu.org/graphics/empowered-by-gnu.svg
Source page: http://www.gnu.org/graphics/heckert_gnu.html
License: GFDL 1.3, the Free Art License, or under CC-BY-SA 2.0

## Name Suggestion

fa-gnu

## Use Case

Use for GNU project or symbol of Free Software (ethic and philosophy).

**Comment by alex-tee** [comment]
+1 really need a GNU icon
