### ISSUE TITLE
code point mismatch of glyph file-epub

### ISSUE THREAD

**Issue by mgieseki** [ForkAwesome/Fork-Awesome#147]
According to `icons.yml`, the code point of `file-epub` is supposed to be F320:
https://github.com/ForkAwesome/Fork-Awesome/blob/7a0461f29059f583e68b74009e7246563b131f89/src/icons/icons.yml#L7202
This value also appears in the CSS file. However, in `.fontcustom-manifest.json` and the font files the glyph is assigned to F321: 
https://github.com/ForkAwesome/Fork-Awesome/blob/7a0461f29059f583e68b74009e7246563b131f89/src/icons/.fontcustom-manifest.json#L999
https://github.com/ForkAwesome/Fork-Awesome/blob/7a0461f29059f583e68b74009e7246563b131f89/fonts/forkawesome-webfont.svg#L2214
I haven't digged deep enough into the build scripts yet to find the reason for this.

**Comment by xuv** [comment]
@mgieseki Oh, thanks for this. It's a latest addition to the set. And I had some troubles bringing it in. Thanks for the heads up. Will look into this.
