### ISSUE TITLE
Slack icon goes against brand guidelines

### ISSUE THREAD

**Issue by micahilbery** [ForkAwesome/Fork-Awesome#15]
Using the slack hash-mark in monochrome is against the brand guidelines. ([*reference](https://slack.com/brand-guidelines)) The proper logo to use in this set would be this one:

![slack_mark_monochrome_black](https://user-images.githubusercontent.com/10608836/36390978-3c44857c-156a-11e8-9cc9-42351f6b93e7.png)

Which can be downloaded as an svg [here](https://brandfolder.com/slack/attachments/oh0k8y-cyzx60-5nfsw0?dl=true&manifest_digest=p4ernx-a6puz4-8rf49z&resource_key=op6f9hfynpza&resource_type=Brandfolder)

fontawsome 5 solved this by making the proposed one shown above the default one under `slack` and the current one under `slack-hash`. ([*reference](https://fontawesome.com/icons?d=gallery&q=slack%20sl))

**Comment by xuv** [comment]
Oh, thanks for spotting this. Let's change it to that one then. 
For my own understanding of things, it means that fontawesome 5 still goes against brand guidelines with their `slack-hash`. Do I understand this right?

**Comment by micahilbery** [comment]
Yeah, I believe so. I don't think any instance of the `slack-hash` that would follow the brand guidelines. I would imagine they just kept it around for those who wanted the old look.

**Comment by xuv** [comment]
Changed. Thanks for this input.
