### ISSUE TITLE
Icon request: Glider

### ISSUE THREAD

**Issue by oxr463** [ForkAwesome/Fork-Awesome#151]
## Icon

![](http://www.catb.org/hacker-emblem/glider.png "glider")

The glider is a generic, yet easily recognizable symbol among the hacker sub-culture ([1]).

## Name Suggestion

`fa-glider`, `hacker (alias)`

## Use Case

Used as a link on a bio page.

[1]: https://en.wikipedia.org/wiki/Glider_(Conway%27s_Life)#Hacker_emblem

**Comment by diondresschers** [comment]
@oxr463 Hi, I would be happy to make this icon (and I am able). Suggestion s 'fa-gameoflife-glider' (and 'gameofflife-hacker' alias) not a better naming convenstions. With a 'fa-glider' users (and I) would  expect a glider related to aircraft [Glider (aircraft) - Wikipedia](https://en.wikipedia.org/wiki/Glider_(aircraft)) and with 'fa-hacker' they might expect a person that is hacking https://en.wikipedia.org/wiki/Hacker.

With:

* gameofflife-glider
* gameofflife-hacker

The related icons are also more nicely grouped/related.

**Comment by oxr463** [comment]
> @oxr463 Hi, I would be happy to make this icon (and I am able to do so). Suggestion: are 'fa-gameofflife-glider' (and 'gameofflife-hacker' alias) not a better naming conventions.

Perhaps `fa-conway-glider` instead? It looks more readable to me.

Either way seems fine to me.

**Comment by diondresschers** [comment]
@oxr463 fa-conway-glider, seems fine as I never heard of the Game Of Life and/or Conway before... :smiley: A shame the rotating fa-glider doesn't work as nicely as this one: https://upload.wikimedia.org/wikipedia/commons/9/96/Animated_glider_emblem.gif

**Comment by oxr463** [comment]
Wow, that would be sick!

**Comment by diondresschers** [comment]
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css" integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG7aaEY=" crossorigin="anonymous">
<i class="fa fa-glide" aria-hidden="true"></i>

**Comment by InfoLibre** [comment]
The SVG file : https://commons.wikimedia.org/wiki/File:Glider_shadow.svg

**Comment by mbomb007** [comment]
> @oxr463 fa-conway-glider, seems fine as I have never heard of the Game Of Life and/or Conway before... 😃
> 
> A shame the spinning fa-glider doesn't work as nicely as this one: https://upload.wikimedia.org/wikipedia/commons/9/96/Animated_glider_emblem.gif

Hey! That's a great idea! You should add `fa-conway-glider-alt`, which could be the intermediate step. Then, to "animate", someone could alternate showing: glider, glider-alt, glider (rotated mirror), glider-alt (rotated mirror), etc...

**Comment by diondresschers** [comment]
Uh.... I think I have to think of how to implement that... :smile

**Comment by oxr463** [comment]
It might be a nice tribute to the mathematician, who recently passed due to the pandemic.
