### ISSUE TITLE
Icon Request: Open Collective

### ISSUE THREAD

**Issue by connyduck** [ForkAwesome/Fork-Awesome#166]
## Icon

https://opencollective.com/static/images/opencollective-icon.svg

Open collective is a platform where open source projects can collect funding. A lot of projects started using it lately, and it is open source itself.

## Name Suggestion

`open-collective`

## Use Case

An Open Source Project would link to their Open Collective page with the icon.

**Comment by diondresschers** [comment]
@xuv @tessus I believe this icon request can be closed...

**Comment by xuv** [comment]
@diondresschers indeed. It will be coming in the next release.
