### ISSUE TITLE
All icons post 1.0.11 are missing in scss files

### ISSUE THREAD

**Issue by eidsonator** [ForkAwesome/Fork-Awesome#168]
When importing the project to my global scss file, `<i class="fa fa-dev-to"></i>` was not displaying.  Upon further investigation I discovered that that the `.fa-dev-to:before` selector was not defined in the scss directory.  

I am submitting a pull request to remedy this situation.

Thanks for the great fork!

**Comment by xuv** [comment]
Thx for finding this one. As mentioned in the PR #169 comment, a lot more icons are missing from the scss files.
