### ISSUE TITLE
Icon request: fa-sass

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#170]
## Icon

FA example: https://fontawesome.com/icons/sass?style=brands

## Name Suggestion

`fa-sass`, `fa-scss`

## Use Case

The same as any language like PHP/JS/CSS and the fact that some may switch from FontAwesome to ForkAwesome while still needing the `fa-sass` icon.

**Comment by diondresschers** [comment]
@Berkmann18 This icon was a 'Walk in the Park' :+1: Thanks to Sass: [Sass: Brand Guidelines](https://sass-lang.com/styleguide/brand) It even included a license for usage! I've created two icons btw. The wordmark suggested by you: 'sass-alt' and the icon 'sass'
