### ISSUE TITLE
Icon request: fa-markdown

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#171]
## Icon

FA example here: https://fontawesome.com/icons/markdown?style=brands

## Name Suggestion

`fa-md`, `fa-markdown`.

## Use Case

Same as for other languages and the fact that it will not deter people from switching from FontAwesome to ForkAwesome.

**Comment by diondresschers** [comment]
Hi @Berkmann18 , I've created the Markdown icon and created a Pull Request for it. https://github.com/ForkAwesome/Fork-Awesome/pull/230/commits/da8b75581e26d85cb0be66fff12bc61bf4bdabee
