### ISSUE TITLE
Icon request: fa-csharp

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#174]
## Icon

MFizz example: http://fizzed.com/oss/font-mfizz/icon-csharp

## Name Suggestion

`fa-csharp`, `fa-c-sharp`, `fa-cs`.

## Use Case

Same as C/Python/...

**Comment by diondresschers** [comment]
Hi, as far I can see there is no official csharp logo from Micrsoft. I've recreated a logo based on this one: [Get Coding Made Easy: C# - Microsoft Store](https://www.microsoft.com/en-us/p/coding-made-easy-c/9nblggh4pzql?activetab=pivot:overviewtab). The logo is represented on a Microsoft website and at least micorosoft the logo to exist there :smile:

**Comment by Berkmann18** [comment]
I'm aware of the lack of official ones and saw one that was used in several places like the one on http://konpa.github.io/devicon/ which can be found at https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png

**Comment by diondresschers** [comment]
Hi @Berkmann18, thank you for your feedback! Yesterday before your reaction I already created an Icon and pull request (though I referred to issue #175 and not this one #174. I did what I thought was best. Here's the Icon I recreated: https://github.com/diondresschers/Fork-Awesome/blob/master/src/icons/svg/csharp.svg

Let me know if you have a strong urge for another icon that resembles csharp the best. Perhaps a screenshot a possible tiny csharp icon in the MS programming environment?

For an Icon I rather use information/logos from Microsoft, as they hopefully know best what Icon is 'an' original :rofl: 

I've also searched in the MS Visual Studio Coce Marketplace for 'csharp'. At this at least is an 'interesting' logo from an extension by our friends at Microsoft:
https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

**Comment by Berkmann18** [comment]
> Hi @Berkmann18, thank you for your feedback! Yesterday before your reaction I already created an Icon and pull request (though I referred to issue #175 and not this one #174. I did what I thought was best. Here's the Icon I recreated: https://github.com/diondresschers/Fork-Awesome/blob/master/src/icons/svg/csharp.svg

You could always the "Close #..." comment in the PR :wink:.

> Let me know if you have a strong urge for another icon that resembles csharp the best. Perhaps a screenshot a possible tiny csharp icon in the MS programming environment?

That icon looks fine to me.

**Comment by diondresschers** [comment]
Hi @Berkmann18, 

For me it is good to hear that the logo looks fine to you!

Thank you for your tip, but actually I already used the Close and Issue number...

But then it would be handy if I would use the correct number :rofl: 

```
dion@desktop:~$ history | grep -e \#175
 1794  git commit -am "Added heroku icon. Closes #175"
 1853  git commit -m "Created sharp icon. Closes #175"
```

**Comment by Berkmann18** [comment]
You're welcome.
You can always rectify that in later commits or the PR body or now link the PR with the issue :grin:.

**Comment by diondresschers** [comment]
#
b787462
