### ISSUE TITLE
Icon request: fa-unity

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#178]
## Icon

MFizz example: http://fizzed.com/oss/font-mfizz/icon-unity

## Name Suggestion

`fa-unity`.

## Use Case

It's a popular game engine (namely among C# devs) which is valuable as a skill so having a FA icon for it would be awesome.

**Comment by diondresschers** [comment]
Hi @Berkmann18 , I've created the Unity icon and a Pull Request. https://github.com/ForkAwesome/Fork-Awesome/pull/230/commits/62b6efc1e1f8c21e7f28d74ba34127ce9adc4e5a

**Comment by Berkmann18** [comment]
Which PR? The commit hash you gave doesn't seem linked to one.
