### ISSUE TITLE
Icon Request: fa-artstation

### ISSUE THREAD

**Issue by micahilbery** [ForkAwesome/Fork-Awesome#18]
Please consider adding the Artstation logo. Use cases would be for artist that want to link their Artstation portfolios. The official branding is available [here](https://cdna.artstation.com/misc/artstation_logos.zip). It's all Adobe Illustrator files though so I have converted the logo mark to an svg to make it easier.
[ArtStation-logomark-dark.zip](https://github.com/ForkAwesome/Fork-Awesome/files/1740814/ArtStation-logomark-dark.zip)

Preview of the above zipped svg:
![artstation-logomark-dark](https://user-images.githubusercontent.com/10608836/36434814-92be2a3c-1625-11e8-99c6-fa864e7c1a83.png)

**Comment by xuv** [comment]
@micahilbery Great. Thanks for this and the conversion to SVG.

Quick question, would you consider being a contributor to this project? I'm in the process on writing a guide on how to add icons. But how do yo feel about trying to do it? I'd be happy to answer your questions here on in a private chat on Mastodon for example.

Let me know what you think

**Comment by micahilbery** [comment]
@xuv Yeah, I'd definitely help when/where I can. I was actually getting ready to message you on mastodon and ask how to add icon's and I would just submit PRs lol. I'm @micahilbery@mastodon.social and here or there whichever is fine with me.

**Comment by xuv** [comment]
Well, let's go through this together here and see if others want to follow.
Well, you will need to follow the README to install a few things. Should be straightforward if you have used npm and bundle already. But don't hesitate to ask questions.

After that, adding an icon requires a few steps:

1. Add a clean SVG in the `src/icons/svg` folder and run `make` from the `src/icons` folder. (I'll try to simplify that step in the future. This will build the icon files and a visual test file you will find in `src/icons/forkawesome`. At this point check the visual test file and look for your icon. It will provide visual feedback on the position and look of it compared to the others. You will probably need to make a few corrections to your SVG but maybe not if you are lucky.

2. When you are satisfied, you'll see that the process has automatically assigned a unicode codepoint for that new icon. And you will have to copy that info at the bottom of the `icons.yml` file. This file is used to build the documentation and the CSS, LESS, etc. See how the other icons are mentioned. And what type of data and naming you will have to add. Once that is done, you can run `npm run dev` to see the documentation being built locally and check that everything is ok with that new icon.

You don't need to complete these 2 steps to do a pull request. Already step one would be great. Let me know what feels comfortable for you. And I'll certainly appreciate your feedback on how all this works. This will help write the documentation for others to contribute.

**Comment by micahilbery** [comment]
I'm having trouble building it with `make` I'm getting this error:
```
Cleaning up SVG files...
svgo --quiet --pretty --config=svgo_config.json --folder=svg
make: svgo: Command not found
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 127
```

**Comment by xuv** [comment]
Oh, it seems it can't find `svgo`. That seems to be the problem.
Did you do `npm install` from the root directory of the project?

**Comment by micahilbery** [comment]
Yep :/ I even tried to install svgo seperately but still get the same error.
```
micah@tomato:~/Projects/Fork-Awesome$ npm install
up to date in 0.193s
micah@tomato:~/Projects/Fork-Awesome$ npm install --save-dev svgo
+ svgo@1.0.4
updated 1 package in 1.079s
```

**Comment by xuv** [comment]
Hmmm. That's weird. 
Ok, the [svgo](https://github.com/svg/svgo) docmentation tells us to install it globally on the system. That might be the problem (It can not find it in your system path.)

So may be I should remove it from the dependencies and ask people to install it this way:
`npm install -g svgo`

**Comment by xuv** [comment]
Maybe also that's not really necessary to have people use `svgo`. I like it because it does extra cleaning of the svg file. Removing any unwanted tags and code that could be in there. But it's not absolutely necessary.

If you don't want it. You can just comment the line `# svgo --quiet --pretty --config=svgo_config.json --folder=svg` in the `Makefile`

**Comment by micahilbery** [comment]
Until I can figure out how to get it to work I'll turn it off for now and clean them up in inkscape before I add them with `inkscape --vacuum-defs -z $file --export-plain-svg=$file`.

**Comment by xuv** [comment]
Oh, I did not know this `--vaccum-defs` option from Inkscape. Thx for the tip.

**Comment by micahilbery** [comment]
Another project I contribute to uses the `inkscape --vaccume-def` in a precommit hook so that it cleans the icons on commit.

**Comment by micahilbery** [comment]
Installing svgo globally worked :tada:

**Comment by micahilbery** [comment]
In the `created` field on the `icons.yml` what would be the proper thing to put there? The current version or current version + .1?

**Comment by micahilbery** [comment]
![screenshot from 2018-02-20 15 31 59](https://user-images.githubusercontent.com/10608836/36450349-407b2238-1653-11e8-81ba-7d9bb5ab7af1.png)
It will take a while for me to get the work flow down but all in all it's a pretty streamlined process you've got. I feel like it's pretty easy to make a contribution following your instructions if you have some familiarity with svg icons.

**Comment by xuv** [comment]
I'm thinking of using the current version still for the `created` field. So 1.0

**Comment by xuv** [comment]
Thanks for your input on this. This is really useful. Do you wish to be added as a team member of the project, so you can have direct commit access. Might be better, no?

**Comment by micahilbery** [comment]
No problem. Sure, I'd be happy to be a team member. :smile:

**Comment by xuv** [comment]
Ok, just added you to a team. Let me know if everything works.

**Comment by micahilbery** [comment]
I think it all worked. It let me create a new branch and PR.
