### ISSUE TITLE
Icon Request: Textpattern

### ISSUE THREAD

**Issue by gregorydk** [ForkAwesome/Fork-Awesome#190]
## Icon

![1eb4a627753459 5636a31f33e1c](https://user-images.githubusercontent.com/7804464/57457957-d3fd3080-7270-11e9-81b0-b602a04c9581.png)

## Name Suggestion

fa-textpattern

## Use Case

Textpattern is a CMS.

https://textpattern.com/
"The small content management system that can handle big ideas"

**Comment by diondresschers** [comment]
Hi @gregorydk , I've created the TextPattern icon (just the icon, not the text as this may be too small to view/read). Also created a pull request for this. https://github.com/ForkAwesome/Fork-Awesome/commit/2a6733841f0a6c3f609be618f6a9e2d18d612e4f
