### ISSUE TITLE
Icon request: freebsd

### ISSUE THREAD

**Issue by alex-tee** [ForkAwesome/Fork-Awesome#192]
It's already in font awesome so i guess it can be merged?

## Icon
See https://fontawesome.com/icons/freebsd?style=brands

Personally I would prefer beastie

## Name Suggestion

freebsd

## Use Case

I have a download dropdown with various OSes and I want to include freebsd. see https://www.zrythm.org download button

**Comment by feld** [comment]
You need explicit permission from Kirk McKusick to use any version of that Beastie. Please get his permission or he will use his lawyer. He has to do this to protect Beastie several times a year.

(I have documented permission from him for creation of my avatar, for example)

**Comment by alex-tee** [comment]
i didn't know trademarks were involved with fontawesome icons. I just saw that on their website. I'll remove all trademarked logos from my website. closing the issue since not needed anymore
