### ISSUE TITLE
Icon request: icon-askfm

### ISSUE THREAD

**Issue by mkljczk** [ForkAwesome/Fork-Awesome#195]
## Icon

A brand icon of a popular mainstream Q&A social network

## Name Suggestion

icon-askfm

## Use Case

One would be able to link to their ASKfm profile…

![ASKfm icon](https://ask.fm/apple-touch-icon-180x180.png)

**Comment by diondresschers** [comment]
Hi @mkljczk . It was a but of a trouble to find a 'correct' icon for ASKfm. ASKfm is quite ambiguous with using their logo/icon (apart from their Corona-own on facebook) :smile: Some owls look to the right, some to the left, some have a bigger circle some have a smaller circle. Anyways, I've managed to create an icon, which is basically the same as yours, only faces the other direction. This icon is on their website below.
![Screenshot from 2020-04-05 11-06-51](https://user-images.githubusercontent.com/3883936/78470957-b5781180-772d-11ea-921f-f31bfffb84b6.png)

I've create a pull request for it.
