### ISSUE TITLE
Youtube style ringing bell

### ISSUE THREAD

**Issue by feld** [ForkAwesome/Fork-Awesome#197]
## Icon

![](https://user-images.githubusercontent.com/48891420/55279922-a70e4300-52ec-11e9-9b0c-893752ab791f.png)

![](https://user-images.githubusercontent.com/48891420/55279923-a83f7000-52ec-11e9-805c-e8e3113e5719.png)

## Name Suggestion

ringing bell?

## Use Case

Useful for identifying that you're subscribed for notifications to something

**Comment by xuv** [comment]
@feld Great idea and thanks for the submission.

For anynone who would like to pick up this one, we already have a [bell](https://forkaweso.me/Fork-Awesome/icon/bell/). I'd suggest to start from there to have the 'ringing' version of it.
