### ISSUE TITLE
ORCiD logo

### ISSUE THREAD

**Issue by dyamon** [ForkAwesome/Fork-Awesome#210]
## Icon

I'm checking with you if this is even possible.

I'd like to have the ORCiD iD ([https://orcid.org/](https://orcid.org/)) in the font, but I'm not sure if it is possible.
Here is the repo with the logo

[https://figshare.com/articles/ORCID_iD_icon_graphics/5008697](https://figshare.com/articles/ORCID_iD_icon_graphics/5008697)

and here the "Trademark and iD Display Guidelines" page

[https://orcid.org/trademark-and-id-display-guidelines](https://orcid.org/trademark-and-id-display-guidelines)

In particular they say:

> A black and white version of the iD icon is available solely for black and white printing use.

Does this mean we cannot have a black and white version in the font?

## Name Suggestion

`fa-orcid`

## Use Case

Linking personal ORDiD in a personal/academic webpage.

**Comment by Bertbk** [comment]
I cannot help about the right to do this icône or not. Before this logo is merged (or not) in fork awesome, you can use [academic icons](https://jpswalsh.github.io/academicons/) which provides the Orchid Id (and many other).

**Comment by Bertbk** [comment]
I submit a pull request in ForkAwesome. In the mean time, you can fin the ORCiD icon in [Font Awesome v. 5.11.2](https://fontawesome.com/icons/orcid?style=brands) (very recent!) and is (from a long time) in [Academicons](https://jpswalsh.github.io/academicons/)

**Comment by dyamon** [comment]
Thanks, I was more concerned about the rights to include it, but it seems like it's already included in other relevant icon fonts... I'm still not sure about that statement about the black and white version.

Also the link I posted clearly references the Academicons website and state that you need to apply a specific color to the icon to comply with their guidelines.

**Comment by Bertbk** [comment]
When using it, you are supposed to colorized the orcid logo with their particular green color (instead of b&w). In practice, it means applying a css on it:
```html
<i class="ai ai-orcid" style="color:#A6CE39;"></i>
```
or with font awesome
```html
<i class="fab fa-orcid" style="color:#A6CE39;"></i>
```

**Comment by dyamon** [comment]
Yeah I know how to color an icon. My point is that you cannot force the color with this font (since is a b/w font), so if you use ForkAwesome (or even Academicons) without reading the guidelines you might not comply with them.

Again, this is the only reason with I didn't file a pull request in the first place.

**Comment by diondresschers** [comment]
Hi @dyamon @Bertbk , I was busy creating the ORCID icon, then I've noticed the Icon already existed in this Repo (guessed I've missed the 'Merged button' :smile:). The icon with the name 'orcid' is not yet listed on https://forkaweso.me/Fork-Awesome/icons/. Do you know about the update policy of that URL? Shame it doesn't update automatically from this repo.

**Comment by dyamon** [comment]
You are right! Even a previous contribution of mine (`volume-muted`) is missing. I think the building process generates the new list, but it is never deployed. Just guessing tho.

**Comment by Bertbk** [comment]
> Yeah I know how to color an icon. My point is that you cannot force the color with this font (since is a b/w font), so if you use ForkAwesome (or even Academicons) without reading the guidelines you might not comply with them.
> 
> Again, this is the only reason with I didn't file a pull request in the first place.

Sorry I missed your answer. You're right, but it'the same for every "font", as FontAwesome (except they now have 2-colors font).

**Comment by dyamon** [comment]
For the ORCiD logo FontAwesome has a note about proper use of the trademark ([here](https://fontawesome.com/icons/orcid?style=brands))

**Comment by diondresschers** [comment]
I wonder how copyright laws apply when referring to or making icons where copyright apply. Would be handy in ForkAwasome to refer all 'Brand Icons' to refer to with the addition of "-c", so in stead of 'orcid' it will be 'orcid-c', so you can more easily see when the icons you use are actually not Open Source under the Font Awesome SIL [SIL Open Font License (OFL)](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

**Comment by diondresschers** [comment]
Okay, now it is more easily to check Live what the status is about the Icon-count and availability of the 3 different sources.

Those 3 sources are:

1. ForkAwesome website
1. ForkAwsome github repo
1. My local ForkAwesome forked repo


---

[Fork Awesome Icons](https://forkaweso.me/Fork-Awesome/icons/)
The complete set of 744 icons in Fork Awesome 1.1.7

---

[Fork-Awesome/README.md at master · ForkAwesome/Fork-Awesome](https://github.com/ForkAwesome/Fork-Awesome/blob/master/README.md)

Fork Awesome is a full suite of 779 pictographic

[Fork-Awesome/src/icons/svg at master · ForkAwesome/Fork-Awesome](https://github.com/ForkAwesome/Fork-Awesome/tree/master/src/icons/svg)

---

[Fork-Awesome/README.md at master · diondresschers/Fork-Awesome](https://github.com/diondresschers/Fork-Awesome/blob/master/README.md)

"Fork Awesome is a full suite of 779 pictographic"

[Fork-Awesome/src/icons/svg at master · diondresschers/Fork-Awesome](https://github.com/diondresschers/Fork-Awesome/tree/master/src/icons/svg)

**Comment by diondresschers** [comment]
I guess @xuv and @tessus have other priorities in life now than Fork Awesome, and I will keep updating my local Repo for life, but if there is hardy a sign of life, I will raise an issue if they could use additional help.

**Comment by tessus** [comment]
It's a bit more complicated than that. I do have commit access to this repo, but xuv decides on what is added or not.

Furthermore there's currently a duplicate codepoint and I sent him a message a while back. But I'm not sure, whether he got it or not, since I never got a reply.

**Comment by diondresschers** [comment]
@tessus Perhaps we can help with the duplicate codepoint. 

Futhermore there may be again a merge-conflict due to the double entries 'f33a', for two pull requests:

'boardgamegeek-icon
[Added boardgamegeek icon · ForkAwesome/Fork-Awesome@552adaa](https://github.com/ForkAwesome/Fork-Awesome/commit/552adaaf78df6468a43f4c7817a6b64fe00c76e3)

and

'riot'-icon 
[Adding Riot icon by rodolpheh · Pull Request #232 · ForkAwesome/Fork-Awesome](https://github.com/ForkAwesome/Fork-Awesome/pull/232)



riot
57f02c3 
f33a
