### ISSUE TITLE
Icon request: icon-sketchfab

### ISSUE THREAD

**Issue by andycuccaro** [ForkAwesome/Fork-Awesome#212]
## Icon

Official colored icon: 

![image](https://user-images.githubusercontent.com/54337672/65634563-dd373180-dfb4-11e9-94ff-dfafc8dfca35.png) 

Official monochrome version: 

![image](https://user-images.githubusercontent.com/54337672/65634611-ffc94a80-dfb4-11e9-8e5a-2ed995d96686.png)

(downloadable officially [here](https://static.sketchfab.com/img/press/logos/logo-black.zip) in both .png and .ai form -the .ai file can be opened in Inkscape just fine-)

## Name Suggestion

`fa-sketchfab` or `sketchfab`

## Use Case

Sketchfab is a website for viewing and sharing 3D models online in real time. It's widely used for 3d artists, heritage organizations, and online products' stores.

Like many brand icons, this icon would be useful for those building a portfolio and including a pingback to Sketchfab, or for "powered by..." buttons, etc.

**Comment by diondresschers** [comment]
Hey @andycuccaro 
I've created the requested icon:
https://github.com/ForkAwesome/Fork-Awesome/pull/230/commits/a2d003b8083b506c4a52560b62408110fbeb61fb

**Comment by andycuccaro** [comment]
Thanks a lot! :)
