### ISSUE TITLE
Icon request: home-assistant

### ISSUE THREAD

**Issue by inputsh** [ForkAwesome/Fork-Awesome#214]
## Icon

![images](https://user-images.githubusercontent.com/4890548/67972493-15164200-fc0f-11e9-905f-7c9018641ef6.jpeg)

[Home Assistant](https://www.home-assistant.io/) is by far the coolest open source IoT service. Its goal is to combine IoT devices into one interface, which can't be done using other, more proprietary platforms. With 27.8k stars, it is within top 200 most starred projects on GitHub.

## Name Suggestion

fa-home-assistant fa-hassio (alias)

Hass.io is a set of images for single-board computers to get Home Assistant running with as little friction as possible. 

## Use Case

Linking to configs, or within a myriad of custom integrations, plugins and themes, most of which are available through the [community store](https://hacs.xyz/).

**Comment by diondresschers** [comment]
Hi @aleksandar-todorovic , I've created the home-assistant icon (with alias) and created a pull request.
[Created home-assistant icon. · ForkAwesome/Fork-Awesome@afec538](https://github.com/ForkAwesome/Fork-Awesome/commit/afec538258b53cc521ca794f462ef7acd2cd5fc1)
