### ISSUE TITLE
Icon request: The rest of the creative-commons pack

### ISSUE THREAD

**Issue by inputsh** [ForkAwesome/Fork-Awesome#215]
## Icon

All of them could be downloaded from these links: [svg](https://mirrors.creativecommons.org/presskit/icons/cc-icons-svg.zip), [eps](https://mirrors.creativecommons.org/presskit/icons/cc-icons-eps.zip), [png](https://mirrors.creativecommons.org/presskit/icons/cc-icons-png.zip).

## Name Suggestion

* `fa-creative-commons-by`
* `fa-creative-commons-nc`
* `fa-creative-commons-nc-eu`
* `fa-creative-commons-nc-jp`
* `fa-creative-commons-sa`
* `fa-creative-commons-nd`
* `fa-creative-commons-zero`
* ...

## Use Case

In a combination with the already-existing `fa-creative-commons` to indicate the license of a work.

My example would look like:

```html
<p>This work is licensed under 
  <a href="https://creativecommons.org/licenses/by-sa/4.0/">
    <i class="fa fa-creative-commons"></i> 
    <i class="fa fa-creative-commons-by"></i> 
    <i class="fa fa-creative-commons-sa"></i> 4.0
  </a>.
</p>
```

Using forkaweso.me as an example, it'd look like this:

```html
Documentation is licensed under 
  <a href="http://creativecommons.org/licenses/by/3.0/">
    <i class="fa fa-creative-commons"></i>
    <i class="fa fa-creative-commons-by"></i> 3.0
  </a>
```

Note that font-awesome [supports this use case](https://fontawesome.com/icons?d=gallery&q=creative-commons) in the free version since v5.0, and it's effectively the only thing I'm missing since I've made the switch.

**Comment by diondresschers** [comment]
Hi @aleksandar-todorovic 
I've also missed myself the rest of the CC icons when I was rendering an PDF based on Markdown when I wanted to license my work as CC BY-SA...

**Comment by diondresschers** [comment]
I've created all requested icons:cc-by, cc-nc-eu, cc-nc-jp ,cc-nc, cc-nd, cc-pd, cc-remix.svg, cc-sa, cc-share & cc-zero

[Added boardgamegeek icon by diondresschers · Pull Request #230 · ForkAwesome/Fork-Awesome](https://github.com/ForkAwesome/Fork-Awesome/pull/230/commits/1ada8bf7eefc4d9d1b724f6ecf743df41ff95c9c)

**Comment by diondresschers** [comment]
Only the original icon didn't match the original Logo from Creative Commons. There are three options we can do:

1. Leave it. It's just the way it is, somethings will never change... (s :musical_note: )
2. Update the exisiting icon, but this might influence other people's projects a tiny bit...
3. Create an additional/alternative icon and refer to this as fa-creative-commons-alt

![Screenshot from 2020-04-04 07-07-26](https://user-images.githubusercontent.com/3883936/78419141-03641b00-7643-11ea-9a8f-17893a0510c9.png)

**Comment by diondresschers** [comment]
ps: my naming scheme is a bit different:
<i class="fa fa-cc-cc"></i>
<i class="fa fa-cc-by"></i>
<i class="fa fa-cc-nc"></i>
<i class="fa fa-cc-nc-eu"></i>
<i class="fa fa-cc-nc-jp"></i>
in stead of: 
<i class="fa fa-creative-commons-by"></i>

**Comment by diondresschers** [comment]
I've also created 'fa-cc-cc' (alias: 'fa-creative-commons-alt') which is actually the correct Creative Commons logo.
