### ISSUE TITLE
Icon request: icon-funkwhale

### ISSUE THREAD

**Issue by DeadSuperHero** [ForkAwesome/Fork-Awesome#216]
## Icon

![funkwhale-logo](https://user-images.githubusercontent.com/401560/68549632-09214180-03c0-11ea-8fb7-8aedf0427dd8.png)

See logo guidelines here: https://funkwhale.audio/en_US/logos/

## Name Suggestion

fa-funkwhale

## Use Case

Funkwhale is a federated social platform similar to GrooveShark, and holds the potential for musicians to self-host their own music in federated networks.

**Comment by Wdavery** [comment]
I think they need to release a monochrome icon before it can be added here. As per their guidelines, you can't modify the colour in any way.

**Comment by EliotBerriot** [comment]
Hi, Funkwhale maintainer here, thank you @DeadSuperHero for opening this request. We'd love to see our logo added to Fork Awesome (which we're using on some of our sites)!

I've pushed a monochrome version of our icon at https://funkwhale.audio/logos/ (direct link is https://funkwhale.audio/img/logos/icon-monochrome.svg), I hope it helps with the inclusion in Fork Awesome :)

Let me know if I can do anything else to help!

**Comment by tessus** [comment]
As long as we have the offical permission to include the icon we are good. We certainly do not want to fight a trademark dispute or face legal action against ForkAwesome. ;-)

The following is obvious though: _We'd love to see our logo added to Fork Awesome_

@xuv how do we handle Icon requests again? Do they have to be labelled as icon request, before we can work on them? It's been a while, so I can't remember the process.

**Comment by xuv** [comment]
@tessus We're not super consistent with the "icon request" badge lately. We do support a lot of ActivityPub based projects, so adding Funkwhale logo sounds like a must. If you want to pick it up.

**Comment by tessus** [comment]
Sure, will do later this afternoon. Just have to get a few more hours of sleep now....

**Comment by EliotBerriot** [comment]
Thanks @tessus :heart:

**Comment by tessus** [comment]
You are very welcome!
