### ISSUE TITLE
Ideal icon size?

### ISSUE THREAD

**Issue by laurent22** [ForkAwesome/Fork-Awesome#219]
It seems that there's an ideal font size for the icons, at which it is rendered cleanly. For example, this is the down arrow at 12px:

![image](https://user-images.githubusercontent.com/1285584/70756610-ebcff200-1d34-11ea-92ee-fee272fb08e5.png)

and at 16px:

![image](https://user-images.githubusercontent.com/1285584/70756556-cc38c980-1d34-11ea-9ede-61cb9253f4fa.png)

so it doesn't look very good as the bottom border is wider than the top one and vice-versa.

However if I set it to 14px it looks fine:

![image](https://user-images.githubusercontent.com/1285584/70756648-0609d000-1d35-11ea-9df4-e0b7cf8f6d34.png)

So I'm wondering how to know at what size a particular icon should be rendered to look good? Is that documented somewhere?

Or perhaps are there some font settings that should be turned on (eg via css) to make sure it look good at any size?

**Comment by xuv** [comment]
@laurent22 very good question. 

Which browser are you doing this screenshot from?

**Comment by laurent22** [comment]
This was in an Electron application, so Chrome I guess.

**Comment by xuv** [comment]
Thank you for sharing that. It's worth doing some tests. It sounds that 14px might be a good answer if we consider when the project started. 14px font size for text was kind of the standard at the time. 

Maybe we could run some more tests with different browsers and CSS settings and see what we find. What do you think? Would you like to take on that task?

**Comment by laurent22** [comment]
Unfortunately I wouldn't have time to look into this. For now I'm happy to use whatever size appears to work well in a given context.

**Comment by xuv** [comment]
Thx. I will close that isssue for now then.
