### ISSUE TITLE
Tor icons is not avaliable

### ISSUE THREAD

**Issue by wioxjk** [ForkAwesome/Fork-Awesome#224]
Excuse me if I am being completely wrong here, but according to this pull request that was merged:

https://github.com/ForkAwesome/Fork-Awesome/pull/188

The icon "tor-onion" should be in forkawesome. But I fail to see it being in production yet.
Why?

**Comment by tessus** [comment]
The Tor icon is there, but it seems that its unicode id is not unique.

Hey @xuv, we are using the codepoint `f32d` for the following 2 icons:

- `tor-onion`
- `bell-ringing`

**Comment by diondresschers** [comment]
Hi @wioxjk and @tessus , I've corrected tor-onion codepoint from f32d to f32e in the .yml file and created a Pull Request.

**Comment by wioxjk** [comment]
Awesome @diondresschers !
Thanks!
