### ISSUE TITLE
Icon request: Nordcast icon

### ISSUE THREAD

**Issue by koyuawsmbrtn** [ForkAwesome/Fork-Awesome#227]
**Repo:** https://git.koyu.space/koyu/nordcast
**Website:** https://nordcast.app

**SVG file:** https://git.koyu.space/koyu/nordcast/raw/branch/master/nordcast_logo.svg

![grafik](https://user-images.githubusercontent.com/40538332/75103057-aa41aa00-55f5-11ea-983a-c890d10bca7a.png)

**Comment by diondresschers** [comment]
Hi koyuawsmbrtn, I've created the icon.  https://github.com/diondresschers/Fork-Awesome/blob/master/src/icons/svg/nordcast.svg Now waiting for the big merge...

**Comment by koyuawsmbrtn** [comment]
Hey @diondresschers the icon looks kinda cropped. Is this normal?
