### ISSUE TITLE
Icon Request: icon-boardgamegeek

### ISSUE THREAD

**Issue by SpencerDub** [ForkAwesome/Fork-Awesome#228]
This could be used in reference to [BoardGameGeek](https://boardgamegeek.com/), which is the most popular board game fan site on the web. I see myself using it on my website to link to my BoardGameGeek profile and wishlist.

While I haven't been able to find an official SVG of the logo, I made one by tracing the logo from another official BGG image. I can't seem to upload SVG files to an issue, though, so here it is as a 512x512 PNG:
![BGG logo orange512](https://user-images.githubusercontent.com/4674927/75132442-cc860700-568b-11ea-963d-5705ae95db4c.png)

**Comment by diondresschers** [comment]
Hi Spencer, I've created an icon for this. Now waiting for the approval from Fork Awesome. https://github.com/diondresschers/Fork-Awesome/blob/master/src/icons/svg/boardgamegeek.svg
