### ISSUE TITLE
fa-buymeacoffee

### ISSUE THREAD

**Issue by thomasbnt** [ForkAwesome/Fork-Awesome#229]
## Icon

Add [Buy Me a Coffee](https://www.buymeacoffee.com/downloads) icon.

[Link to Branding Pack](https://www.buymeacoffee.com/downloads)

Important to show a true link for Buy Me a Cofee sign for donate to developer, artist, and more others!

## Name Suggestion

**fa-buymeacoffee**

**Comment by diondresschers** [comment]
Created an icon for you and all coffee-lovers ;)

**Comment by thomasbnt** [comment]
No update about that? 😶
