### ISSUE TITLE
Icon request: icon-LaTeX

### ISSUE THREAD

**Issue by gladonias** [ForkAwesome/Fork-Awesome#231]
I've just looked around the website, nothing related to TeX or LaTeX.

## Icon
Here's the logo already in svg: [LaTeX](https://commons.wikimedia.org/wiki/File:LaTeX_logo.svg).

## Name Suggestion
LaTeX or LaTeX-Project

## Use Case
Anyone who would like to write about LaTeX in their website without the confusion with the raw material for rubber :)

**Comment by diondresschers** [comment]
Hi @gladonias I think LaTeX logo is more a wordmark [1] than a logo that fits nicely into a square that actually Fork-Awesome requires. Could you also consider just the TeX logo? 

https://user-images.githubusercontent.com/5700795/49007377-3bac3d00-f163-11e8-8172-cdad5fde4c8c.png

References:
[1] [The 7 types of logos (and how to use them) - 99designs](https://en.99designs.nl/blog/tips/types-of-logos/)

**Comment by diondresschers** [comment]
PS: Somewhat same discussion over here: :D
[Icon Request - TeX / LaTeX Icon · Issue #1614 · Templarian/MaterialDesign](https://github.com/Templarian/MaterialDesign/issues/1614)

**Comment by diondresschers** [comment]
@gladonias Now there is something TeX related :smiley: .

**Comment by gladonias** [comment]
That is great, @diondresschers, thank you :D
