### ISSUE TITLE
Bunny Icon

### ISSUE THREAD

**Issue by Jadziara** [ForkAwesome/Fork-Awesome#233]
## Icon

 no image available: Bunny seen from the front with big ears and eyes

## Name Suggestion

 Crazy Bunny

## Use Case

Represent crazy idea / mood / Bunny :)

**Comment by diondresschers** [comment]
A bunny sounds logical as it's almost Easter. I can make something like this. 2 icons. One frontside and one backside.
![rabbit](https://user-images.githubusercontent.com/3883936/78598097-f1ef5e80-784e-11ea-8710-841c29b1ad32.jpg)

**Comment by The-EDev** [comment]
Seems like the fa-bunny icon has been added, though https://forkaweso.me/Fork-Awesome/icons/ doesn't show it, maybe update the site and close this issue?

**Comment by diondresschers** [comment]
@The-EDev - I don't have the rights to update anything, I can only create pull requests from my own repository...
