### ISSUE TITLE
Let me know if you need any help...

### ISSUE THREAD

**Issue by diondresschers** [ForkAwesome/Fork-Awesome#235]
Last days I have made a lot of icons based on issues by different users, and I have created many Pull Requests (https://github.com/ForkAwesome/Fork-Awesome/pull/230).

I've noticed there is not much activity and maintaining in this Repository and the CDN which resulted in some issues #234, #224, #210 & #218 and (future) merging problems.

The difference in number in Icons are viewable when you check different repo's, the website and the CDN:
https://github.com/ForkAwesome/Fork-Awesome/issues/210#issuecomment-609373406

I have already started my own Fork Awesome fork, just as a learning experience, due to some different views and because I want to use the actual product and newly created icons in real life.

Please let me know if you need any help, and I will see what I can do.

**Comment by xuv** [comment]
Hello @diondresschers Thanks for reaching out.

Indeed, your help would be much appreciated. Sorry for having been unresponsive. Let's work together to integrate your big PR into this and release a new version of the font.

Julien

**Comment by diondresschers** [comment]
Hi @xuv, no worries. I was a bit worried, but I am happy that there is still (some) life in ForkAwesome.  My local server/repo all runs fine, so (hopefully) merging the PR's is not a big issue. How can I assist as I don't have any additional rights in this Repo!?

**Comment by xuv** [comment]
@diondresschers There is life into this project. And thanks a lot to you for that.

I've made a few comments on the pull request you created. Let me know how you would like to address them. If you want me to collaborate with you on this. Or if I let you make some fixes and you let me know when you are ready. Which ever way works best for you.

Thanks again for your patience.

**Comment by diondresschers** [comment]
Hi @xuv as you now a new PR has been created https://github.com/ForkAwesome/Fork-Awesome/pull/249

How do you think about:

Short term:

1. Merging my PR.
2. Updating the Website and jsDelivr CDN.
3. Starting with closing Issues, that can be closed.
4. I will start working on other Icon-request, so also they can also be closed.
5. Make a structure (with regular updates), and vision for now and the long term how to handle/tackle this project, so Fork Awesome can stay awesome for now and the future

**Comment by xuv** [comment]
Hello @diondresschers 

All good points. Thank you for raising them.
I will merge your PR. And after that, I'd really like to have a conversation with you and the rest of the team to discuss the point 4 and 5 and how to plan to move forward together.

Thank you for your help and see you soon.

**Comment by diondresschers** [comment]
@xuv Great to hear the PR worked without troubles! let me know when, how and with whom you want to get together for the 'future-proof' Fork Awesome. I guess through all your FA work, you know who want and can join. Maybe raising an Issue give others the opportunity to contribute as well.

**Comment by The-EDev** [comment]
Someone really needs to work on point 3, I'm genuinely having difficulty finding requests for icons that haven't been implemented.

**Comment by diondresschers** [comment]
@xuv I didn't hear anything from you the last 10 months. I hope everything is okay with you. I feel a bit sad as I think Fork Awesome is potentially a great project. I know I could contribute a lot to this project as I didn't see any new merges in this repo or updates in the CDN since a long time. For me you can close this issue as I will continue to work on my own Fork Awesome Fork. in which I have more possibilities to fix and update stuff.

**Comment by shinenelson** [comment]
I would like to volunteer as well.

I can start by triaging open issues.
> 3. Starting with closing Issues, that can be closed.

> Someone really needs to work on point 3, I'm genuinely having difficulty finding requests for icons that haven't been implemented.

I have identified at least a few issues that can be closed since the icons in the requests are already in ForkAwesome.

**Comment by DougInAMug** [comment]
Hey @diondresschers - would you say, with all the recent activity, that we can close this issue?

Hope you're well, miss you in the room! Look forward to welcoming you back when the project is running a bit more smoothly :sweat_smile:

**Comment by diondresschers** [comment]
Yep! This issue can be cloded @DougInAMug ! I see a LOT of activity, so I think I'm not pivotal in this project..  😄👍 

Would be great to come back at a later time. For now I am very happy to see all the activities happening. Kudos!
