### ISSUE TITLE
Icon Request: fa-activitypub

### ISSUE THREAD

**Issue by mray** [ForkAwesome/Fork-Awesome#24]
![image](https://user-images.githubusercontent.com/164785/36536420-36dc186a-17cd-11e8-9341-b5b9449c84e6.png)

I request the addition of the [ActivityPub](https://activitypub.rocks/) icon. It is the emerging [W3C standrard protocol](https://www.w3.org/TR/activitypub/) for decentralized social networking.

### possible usecase:
Personal website linking to an ActivityPub powered webservice like Mastodon, GNUSocial, ... , .... .

> As SVG isn't an allowed attachement format [I zipped up the plain logo](https://github.com/ForkAwesome/Fork-Awesome/files/1747711/ActivityPub-logo-symbol_SW.svg.zip).

**Comment by xuv** [comment]
@mray: I'm all good to add an ActivityPub icon, but since we have Mastodon, GNUsocial and similar already, don't you think people would prefer those than the Activity Pub one? 

Where would you use it?

**Comment by mray** [comment]
@xuv i think you would want it for the same reason you would like a riot.im AND matrix logo. One is the standard, the other an implementation.

I think it is up to personal interest whether you want to advocate you are on the wider ActivityPub network or on a specific server implementation.

Personally I think AP is more important as GNUSocial people can **all** follow Mastodon people. In that case having different icons is rather disruptive imho.
