### ISSUE TITLE
Icon Request: icon-keybase

### ISSUE THREAD

**Issue by mimikun** [ForkAwesome/Fork-Awesome#25]
I request the addition of the Keybase icon. 
It is public key infrastructure.
It is useful credential service.

### possible usecase:
Personal website linking to a Keybase.

### icon image
[icon link](https://keybase.io/images/icons/icon-keybase-logo-48@2x.png)

**Comment by xuv** [comment]
Found the SVG in the FontAwesome icon request: https://github.com/FortAwesome/Font-Awesome/issues/4095
