### ISSUE TITLE
Is it possible to split this Icon-Font?

### ISSUE THREAD

**Issue by cyberpunkbln** [ForkAwesome/Fork-Awesome#253]
Hello,
only a short questions is it possible to split this font into theme based fonts?

Like
1. Web Application Icons
2. Brands
and so on

or give it an special site where your prpject are embeded?

thx

**Comment by cyberpunkbln** [comment]
Cool,
a system like https://remixicon.com/ will be also great.

**Comment by shinenelson** [comment]
Duplicate of #53
