### ISSUE TITLE
src folder missing when npm install

### ISSUE THREAD

**Issue by hugobqd** [ForkAwesome/Fork-Awesome#254]
I need to use SVG files on a project, but the [`/src`](https://github.com/ForkAwesome/Fork-Awesome/tree/master/src) folder is missing when I `npm install ForkAwesome/Fork-Awesome`

https://www.npmjs.com/package/fork-awesome

**Comment by The-EDev** [comment]
not an expert, but this might be because the /src folder is for building the font itself, while the npm package only has the font, a workaround would be to clone this repo, since you want to use the individual SVGs

**Comment by shinenelson** [comment]
This issue is being closed since the reporter has been given a solution that could potentially resolve their issue. And also since there has not been any update since then. If there still is some issue, please re-open this issue.
