### ISSUE TITLE
Icon request: Ubuntu

### ISSUE THREAD

**Issue by paride** [ForkAwesome/Fork-Awesome#255]
## Icon

Artwork for the icon is available here: https://design.ubuntu.com/downloads/ as the "Ubuntu Circle of Friends set for web" in several formats, including EPS.

The artwork is distributed under the Creative Commons BY-SA license.

## Name Suggestion

Just "Ubuntu" will do.

## Use Case

Anything related to this popular GNU/Linux distribution. Same use case of the "Debian" icon. Related: https://github.com/ForkAwesome/Fork-Awesome/issues/256.

**Comment by Hugo-Trentesaux** [comment]
Also see https://simpleicons.org/
