### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by The-EDev** [ForkAwesome/Fork-Awesome#262]
So I initially looked at ForkAwesome because FontAwesome's licence was not what I was looking for (to put it simply).

But it seems there hasn't been a commit since 2 months, the project has been bumped to 1.2.0 but was updated nowhere except on Github, many of the issues have already been resolved but remain open, not to mention the pull requests that still await some form of response.

Is it fair to declare this project Abandoned? I know one of the main focuses is for it to be forkable, but it is still a rally for a lot of people who make and request icons, while a fork of it might not be.

**Comment by tclavier** [comment]
In other terms, @xuv and @tessus do you want some help to cleanup issues and follow contributions ?

**Comment by tessus** [comment]
I tried to reach @xuv without success. I've already suggested to add others as maintainers. I'm not really a graphics guy. I managed to work on a few icons, but it always took me forever.
I have no admin access to the repo, just commit access.

**Comment by tclavier** [comment]
@tessus could you merge pending PR ? I have review https://github.com/ForkAwesome/Fork-Awesome/pull/260 and i can help to review others ... i thinks it's a first step to unlock the situation.

**Comment by tessus** [comment]
Yes, this seems like a good idea. Thanks, I've merged the PR.

**Comment by DougInAMug** [comment]
@The-EDev @tclavier Hello! A small, newish team have formed to try and make something out of this project, in case you're still interested. We're chatting here: https://matrix.to/#/#forkawesome:matrix.org
