### ISSUE TITLE
Create an icon for "Shaarli" ?

### ISSUE THREAD

**Issue by opitux** [ForkAwesome/Fork-Awesome#28]
It would be great if an icon for shaarli was added

![shaarli](https://user-images.githubusercontent.com/9692784/36592752-53184ace-1897-11e8-9f5b-012926ff73e8.png)
I can't upload the svg file :/

Thank you so much for this fork :)

**Comment by xuv** [comment]
@optitux: Good idea. Where can we find the SVG? Do you have an idea?

**Comment by opitux** [comment]
I made one for my personal use but I can't attach it to my messages.
And I don't know much about Github :/

**Comment by xuv** [comment]
@opitux One way to attach it is to zip it first. 
Another way is to copy paste the code of the SVG in the message between:

 \``` your code here  \```

**Comment by xuv** [comment]
Oh, nevermind, I found it here: https://github.com/shaarli/Shaarli/blob/master/doc/md/images/doc-logo.svg

**Comment by xuv** [comment]
Ok, I've added 2 versions of the icon:
 - https://forkawesome.github.io/Fork-Awesome/icon/shaarli/
 - https://forkawesome.github.io/Fork-Awesome/icon/shaarli-o/

Enjoy! ;)

**Comment by opitux** [comment]
Thank you very much :)
Ok for the zip or to copy paste the code of the SVG in the message.
I'm quit stupid ^^
