### ISSUE TITLE
Logo for Lemmy (reddit like service for the fediverse)

### ISSUE THREAD

**Issue by wakest** [ForkAwesome/Fork-Awesome#289]
## Icon

![image](https://user-images.githubusercontent.com/7890201/114214731-50e82780-992a-11eb-9e64-0397c2527b29.png)
just copied the logo from the website but I am sure there is an svg somewhere
you can see the logo in use here https://lemmy.ml/post/59433

Lemmy is a pretty popular fediverse project. I came to file this issue because a project that I use, uses ForkAwesome for their fediverse logos and needs this logo to continue, here is the issue on their side: https://gitlab.com/mugcake/share-freedom-extension/-/issues/2

**Comment by DougInAMug** [comment]
@wakest is there already an SVG version?

**Comment by wakest** [comment]
here are the official SVGs! sorry it took a bit to get them and then remember to post them here
[lemmy-logo-no-border.zip](https://github.com/ForkAwesome/Fork-Awesome/files/6412094/lemmy-logo-no-border.zip)

**Comment by DougInAMug** [comment]
Looks good! :smiley:  Sadly I haven't got round to setting up the dev environment and figuring out the build process, so I won't be personally be able to turn your files into a pull request :disappointed:

**Comment by aguragorn** [comment]
https://duckduckgo.com/press

![image](https://user-images.githubusercontent.com/3759189/129238923-c05b8156-f70c-4e6b-a9bc-ae00e294d714.png)

**Comment by shinenelson** [comment]
Thank you for the URL and the pointer @aguragorn; but did you mean to post this to #189? I think it would be more relevant to that issue than this one.

**Comment by aguragorn** [comment]
> Thank you for the URL and the pointer @aguragorn; but did you mean to post this to #189? I think it would be more relevant to that issue than this one.

You are right, I'm sorry about that. I enjoyed looking at icon requests, and had multiple tabs opened. I'll move my comment.

**Comment by shinenelson** [comment]
> I enjoyed looking at icon requests

We are happy that you looked into the many open https://github.com/ForkAwesome/Fork-Awesome/labels/icon-request. You are welcome to open pull requests for them if you are interested and have the time to contribute.
