### ISSUE TITLE
Icon-request: modern key

### ISSUE THREAD

**Issue by ArthurHoaro** [ForkAwesome/Fork-Awesome#29]
The key icon used in ForkAwesome is a bit old fashioned and an alternative using a simple more modern key could be a good idea.

Something like that:

![687474703a2f2f7777772e7761727769636b73686972652d73656375726974792e636f6d2f696d616765732f6b65792e706e67](https://user-images.githubusercontent.com/1962678/36612300-81980a94-18d6-11e8-88ba-246a068216cb.png)

Old related issue: Font-Awesome/789

**Comment by xuv** [comment]
Great idea. Amazing you found an open issue from 2013 on Font Awesome. Would be pleased to resolve that one.

**Comment by ArthurHoaro** [comment]
I remembered seeing it, Google did the rest of the magic.

**Comment by xuv** [comment]
Modern key is now added to the set. 
Based on your design proposition. Slighly modified to work better at very small sizes. 
You can see it here: https://forkawesome.github.io/Fork-Awesome/icon/key-modern/

If you are happy with this. I will bump the release version, and then you could even use Composer to fetch the Fork Awesome package for Shaarli. If that's something that you find interesting to do.
