### ISSUE TITLE
Community chat?

### ISSUE THREAD

**Issue by DougInAMug** [ForkAwesome/Fork-Awesome#292]
I'm interested in contributing, but I'm not super technically skilled and would be interested to ask a few questions... did anyone think of setting up a Matrix room or Gitter? Would be helpful for someone like me!

**Comment by diondresschers** [comment]
Hi @DougInAMug ,

I hope you can get help here, but I don't have any high hopes as this issue didn't move the way I hoped:
https://github.com/ForkAwesome/Fork-Awesome/issues/235

Let me know if you need any help.

**Comment by DougInAMug** [comment]
@diondresschers I chatted a bit with @xuv on another medium, where they explained they are a bit overwhelmed with the project. As of yet, I haven't got the dev env set up to make pull requests myself, but reading the issue you mentioned it seems a deeper issue is having someone who accepts those PRs. Could you imagine doing that?

**Comment by diondresschers** [comment]
@DougInAMug as far I can see it, there are more than just technical issues.

This has to be done on the technical site:

1. Merging PRs.
2. Updating the Website (https://formaweso.me)
3. Updating the jsDelivr CDN.

If I would agree to do to point 1, the Merging of PRs (if I had the rights), than still somebody capable should perform point 2 and 3.

For this moment, I don't see myself accepting PRs for ForkAwesome.
Beside the technical issues, there are also organizational issues.

For the organizational issues I suggested earlier: 
"*Make a structure (with regular updates), and vision for now and the long term how to handle/tackle this project, so Fork Awesome can stay awesome for now and the future*"

**Comment by DougInAMug** [comment]
@diondresschers would you be interested to chat somehow? There are several methods on my site https://dougwebb.site/ I would suggest making a `forkawesome_unofficial` matrix room if that works for you.

Whether or not you want to step up to a position of responsibility, perhaps you're interested to help figure out how to move it forward.

**Comment by diondresschers** [comment]
@DougInAMug sure, a chat couldn't hurt...

You've got some nice options on your website! 

A Matrix-room sounds great! I'm looking forward to it.

**Comment by DougInAMug** [comment]
Hey, there is now an unofficial, public Matrix room:
- Matrix address: #forkawesome_unofficial:matrix.org
- Element URL: https://app.element.io/#/room/#forkawesome_unofficial:matrix.org

**Comment by diondresschers** [comment]
It would be great if the FormAwesome github members @xuv and @tessus could join. :)

**Comment by DougInAMug** [comment]
@diondresschers did you get my Matrix message about the call tomorrow? Would be great if you can make it!

**Comment by diondresschers** [comment]
Hi Doug, 

I've enabled the E-mail notifications in Matrix, so now I won't miss any updates. 
I can join the call! 
Thanks for the meeting time that suits well (after my Office hours)!

**Comment by DougInAMug** [comment]
Hey @diondresschers did you see we've switched to #forkawesome:matrix.org ?

**Comment by tessus** [comment]
I still don't know what's going on. I've tried to contact @xuv a few times, but no reply.

I don't know what the status of this project is. He's usually the one who cuts new releases and makes decisions. But right now I just don't know anything.

**Comment by DougInAMug** [comment]
Hi @tessus ! A call was had with Xuv last week. Notes from that call are [here](https://codi.kanthaus.online/forkawesome#) and there is a [matrix room](https://app.element.io/#/room/#forkawesome:matrix.org) that was already linked above.

It seems like there are a few new people interested to take over responsibilities, and develop the project further :) How are your feelings? There will be another the week after next: if you're interested, add your availability to this [poll](https://framadate.org/EG24ee3H23SRJaLs)

**Comment by diondresschers** [comment]
> Hey @diondresschers did you see we've switched to #forkawesome:matrix.org ?

After this message of yours, I did... :D

**Comment by DougInAMug** [comment]
Perhaps you're also interested to join the [room](https://app.element.io/#/room/#forkawesome:matrix.org) @n8willis @brendanhowell ?
