### ISSUE TITLE
Website outdated

### ISSUE THREAD

**Issue by DougInAMug** [ForkAwesome/Fork-Awesome#294]
The [Forkawesome website](https://forkaweso.me/Fork-Awesome/) has version 1.1.7, but [this repository](https://github.com/ForkAwesome/Fork-Awesome) is at version 1.2, which introduces (at least) 38 new icons.

Further, the source for the website is not linked anywhere, and the https://github.com/ForkAwesome/forkawesome.github.io website is just a redirect.

**Comment by DougInAMug** [comment]
Closing this issue, because the outdatedness is now a known issue, and is actively being worked on.

Also, the source of the website _is_ linked, since the github repo is linked, and indeed the website source is there alongside the icons.

**Comment by shinenelson** [comment]
In my opinion, we should keep this issue open until we actually fix it ( and let the pull request that fixes it close it :laughing: ).

> the https://github.com/ForkAwesome/forkawesome.github.io website is just a redirect.

The repository's existence itself is misleading. I was misled by it previously too. We should assume that we are probably not the only ones who were misled by it. We could do away with that repository completely when we revamp the website deployment.
