### ISSUE TITLE
The blue in the documentation website is distracting

### ISSUE THREAD

**Issue by ArthurHoaro** [ForkAwesome/Fork-Awesome#30]
I feel like the blue in the documentation website is a bit aggressive and distracting, and I think that choosing a bit more muted color would be better.

**Comment by xuv** [comment]
You're right. It might be distracting. The aggressiveness of it was kind of intentional... as a strong stand for a fork... but we could certainly tone it down a little.

**Comment by xuv** [comment]
I've toned down the saturation and luminosity of the blue on the website. 
Have a look. If it's ok with you, then we can close this issue.

**Comment by ArthurHoaro** [comment]
I'm still not a big fan of the color, but I see your point. I suppose it mostly a matter of personal taste. Thanks for taking my feedback into account.
