### ISSUE TITLE
Icon request: xmpp

### ISSUE THREAD

**Issue by ajdunevent** [ForkAwesome/Fork-Awesome#33]
Greetings!
Thank you for this amazing fork.
I would like to request an XMPP icon.
This would be useful when providing xmpp contact information on a webpage (my use) or to provide the details if a site provides an xmpp service or even as an icon that could open a web-based xmpp client if a site had one.
Some good, free images to base it on are available on the xmpp.org Github:
https://github.com/xsf/xmpp.org/blob/master/xmpp.org-theme/static/images/xmpp-logo.svg
https://github.com/xsf/xmpp.org/blob/master/xmpp.org-theme/static/images/xmpp-logo.png

**Comment by xuv** [comment]
Added the icon to the set. It's in master at the moment. Will be available from the website with the next release. Probably later in the day.

**Comment by ajdunevent** [comment]
Awesome! Thank you very much!

**Comment by Neustradamus** [comment]
Good news :)
Thanks a lot for this!

**Comment by xuv** [comment]
@Neustradamus You're welcome. Don't hesitate to share back with us where you plan to use this.

**Comment by xuv** [comment]
Just released version 1.0.9 of the project. Xmpp is in it.
https://forkawesome.github.io/Fork-Awesome/icon/xmpp/

This also "closes" one of the oldest (Nov 2012) [icon-request still open on Font Awesome today](https://github.com/FortAwesome/Font-Awesome/issues/549).

**Comment by SeveFP** [comment]
Thank you for adding it, that is truly AWESOME :smile:

**Comment by SeveFP** [comment]
Hi @xuv, would it be possible to update the icon to make it look more like the original one?
I realized the icon is thinner and narrower than the [XMPP logo.](https://en.wikipedia.org/wiki/XMPP#/media/File:XMPP_logo.svg)
I would like to have the same one as openwebicons, if possible.

Links for comparison:
http://forkaweso.me/Fork-Awesome/icon/xmpp/
https://pfefferle.dev/openwebicons/icons/ (look for `openwebicons-xmpp`)

Please let me know :)

**Comment by Neustradamus** [comment]
There are little changes about the logo, can you update?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by xuv** [comment]
@Neustradamus Is this the same comment as @SeveFP made?

**Comment by Neustradamus** [comment]
@xuv: Please look date on this link:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by Neustradamus** [comment]
@xuv: Please look date on this link:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by Neustradamus** [comment]
@xuv: Have you updated the icon with good version?
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
- https://commons.wikimedia.org/wiki/File:XMPP_logo_(without_text).svg

In more: @ajdunevent, @xuv, @SeveFP (and all others in the World): Can you add +1 here:
- https://github.com/FortAwesome/Font-Awesome/issues/549#issue-8533733

Thanks in advance.
