### ISSUE TITLE
Incorrect download link on forkaweso.me

### ISSUE THREAD

**Issue by FWDekker** [ForkAwesome/Fork-Awesome#335]
[forkaweso.me](https://forkaweso.me/Fork-Awesome/) has a big "Download" button on it. Clicking it and then confirming by pressing "Fork Awesome 1.2.0" results in a `404: Not Found`.

The reason is that the latest release is called `1.2` but the download link goes to `1.2.0`. Either the download link or the tag should be updated. According to the README, Fork Awesome uses semver, so I think the tag should be renamed (or copied, just to be certain) to 1.2.0.

PS: Happy to see the project is being revived! :D

**Comment by shinenelson** [comment]
Thank you very much for bringing this up @FWDekker. This was a mistake on my part. The maintainers had been talking too much about the **1.2** release that I got too excited when it was finally happening and overlooked semantic versioning when I actually created the tag.

I have now replaced the `1.2` tag with `1.2.0`.

---

> PS: Happy to see the project is being revived!

PS: We are happy to see that people like yourself are enthusiastic to try out the latest version and report back issues. Thank you :heart:
