### ISSUE TITLE
Icon request: Codeberg

### ISSUE THREAD

**Issue by mskf1383** [ForkAwesome/Fork-Awesome#360]
### Acknowledgement

- [X] I have searched through both open and closed issues and confirm that this icon has not been requested earlier.

### Icon

https://codeberg.org/assets/img/logo-small.svg
(its white)

### Name suggestion

Codeberg

### Use-case

fa-codeberg

### Additional information for brand icons

https://codeberg.org/

**Comment by shinenelson** [comment]
The Codeberg icon was merged into the fork-awesome set with #324 even though there was no icon request for it. The icon has not been released yet though; neither is there a date for the next release.

**Comment by mskf1383** [comment]
Thanks!
I don't check pull requests.
