### ISSUE TITLE
Icon request: fa-tipeee

### ISSUE THREAD

**Issue by qwertygc** [ForkAwesome/Fork-Awesome#39]
Hello!
i suggest to add a brand icon. it's « [Tipeee](https://www.tipeee.com/img/pedago/tipeee-tip-btn.png) », a french patreon alternative. 

Regards

**Comment by xuv** [comment]
Hey @qwertygc.
Thank you for your message. Could you please separate those into 2 issues? Let's keep this one for fa-tipeee and create another one fro fa-facebook-messenger.

**Comment by xuv** [comment]
Hey. Sorry for this, but Tipeee does not seem to have their branding all straight....
https://www.tipeee.com/gaki-parody/embed/configure
I have mixed feelings between:

<img width="100" alt="tip" src="https://www.tipeee.com/img/pedago/tipeee-tip-btn.png" > or <img width="103" alt="screen shot 2018-03-02 at 15 29 37" src="https://user-images.githubusercontent.com/192539/36920422-a4c73212-1e2e-11e8-9978-64d39ff8ba7c.png"> or <img width="69" alt="screen shot 2018-03-02 at 15 33 54" src="https://user-images.githubusercontent.com/192539/36920605-2e5d0150-1e2f-11e8-902e-7e47bb381c22.png">

Which one is the right one?

**Comment by qwertygc** [comment]
The number one ?

**Comment by xuv** [comment]
Ok, I've reached to Tipeee support to signal this issue and they encourage the number one. So I'm gonna go down that road.

**Comment by qwertygc** [comment]
think

**Comment by qwertygc** [comment]
Thinks you :-)
