### ISSUE TITLE
Icon request: fa-nodejs

### ISSUE THREAD

**Issue by thomasbnt** [ForkAwesome/Fork-Awesome#45]
The primary icon + pattern green, otherwise it will be too big.

Guidelines : https://nodejs.org/static/documents/foundation-visual-guidelines.pdf
Ressource : https://nodejs.org/en/about/resources/

**.svg file** : 
[nodejs-svg.zip](https://github.com/ForkAwesome/Fork-Awesome/files/1778137/nodejs-svg.zip)

Thank u :+1:

**Comment by xuv** [comment]
@thomasbnt The primary icon in pattren green will just look like a black hexagon when turned into an icon. Icon fonts don't have nuances such as shades of grey or shades of transparency. It's either black or white.

Also, which use case do you see for a Nodejs icon?

**Comment by thomasbnt** [comment]
For example, show skills and yes, just 'Js' marked into the hexagonal.
