### ISSUE TITLE
Icon request: fa-javascript

### ISSUE THREAD

**Issue by thomasbnt** [ForkAwesome/Fork-Awesome#46]
Hi :hand: 

There is not really an official logo for javascript, I found two different types of logos.

Files (1x .ai and 1x .svg): 
[javascript.zip](https://github.com/ForkAwesome/Fork-Awesome/files/1778132/javascript.zip)
 

Preview : 
![preview-logo-javascript](https://user-images.githubusercontent.com/14293805/36941746-0d65c6fa-1f63-11e8-8afa-ab2d28de86db.png)

![Preview](https://i.stack.imgur.com/Mmww2.png)

**Comment by xuv** [comment]
Hello @thomasbnt, so which one is the right one? I believe probably the 2nd one... that's the one I saw the most. But I might be wrong.

Which use cases do you foresee with this icon?

**Comment by thomasbnt** [comment]
To set it up in our skills for example, neither of the two are official, I see them often enough that it is the first or the second.

The first is clean and most detailed, but the second is simple. I don't know ^^

**Comment by Berkmann18** [comment]
The second one is the most used from what I see but the first one goes hand in hand with HTML and CSS's icons, plus there are practically no font icons for the first one whereas the second one was implemented [here for example](mfizz.com/oss/font-mfizz).

**Comment by thomasbnt** [comment]
@Berkmann18 yeah but the second can do well in logo, it is simple and not detailed

**Comment by Berkmann18** [comment]
@thomasbnt True, it's simple and known but it's not consistent with the HTML and CSS icons which are often grouped with it.

**Comment by Berkmann18** [comment]
Should we have a vote on this or what are the next steps to get an `fa-javascript`/`fa-js` icon?

**Comment by xuv** [comment]
Since we have [HTML5](http://forkaweso.me/Fork-Awesome/icon/html5/) already, I feel now that the second one would be better. I doubt it works at small sizes though. But we could try it.

**Comment by Berkmann18** [comment]
@xuv [FA's one](https://fontawesome.com/icons/js?style=brands) seems to scale well for small sizes so I think it's worth trying that one.
