### ISSUE TITLE
Add link to "how to use" in README

### ISSUE THREAD

**Issue by inredmood** [ForkAwesome/Fork-Awesome#48]
I’m not sure it is the right place to ask for this, but I would like to build the project, and followed the "building on fork awesome" instructions, but the: 
`$:/src/icons make` did not work. I have a no such file or directory error (I’m on ubuntu 16.04).

**Comment by inredmood** [comment]
I found out how to make it work, it turned out, I didn’t need to build it, for what I wanted to do.

**Comment by xuv** [comment]
Thanks for your feedback. Indeed we need to improve the documentation about this project and how to build. Any suggestion or comment is welcome.

**Comment by inredmood** [comment]
In my case, I wanted to put mastodon and diaspora icons on my website. I got confused on how to do it, so at first I thought I would need to build the project from the sources, but since I got stuck with the building process, I found a website (framasoft.org) making use of it and found out they were apparently using the min.css files, so I added the css files on my website, and had a 404 on my servers log, for fonts files, so I added them too, and it worked. So, my thought is, maybe it should be explained in the doc.

**Comment by xuv** [comment]
@inredmood Thanks for the feedback. Glad you found your way through. I'm curious where you read the instructions to build it? In the README maybe? There is [a page here explaining the installation process](https://forkawesome.github.io/Fork-Awesome/get-started/). Maybe we should link to it from the README. Let us know how we could improve this?

**Comment by xuv** [comment]
Ok, I've fixed all this in 74d88fb8dc492623e8be32c61c1d358a605a5e77 Thx for your help.
