### ISSUE TITLE
Icon Request : Dogmazic

### ISSUE THREAD

**Issue by Aisyk** [ForkAwesome/Fork-Awesome#49]
Hi !
Is it possible to add the french musique libre plate-form, [Dogmazic.net](http://www.dogmazic.net/) ?
It's musics with creative commons and other licenses.
[http://www.dogmazic.net/](http://www.dogmazic.net/)

**Comment by xuv** [comment]
@Aisyk Sure. 
Could you give us a practical case of the use for that icon?
And also, it would help us if you could point to an SVG version of the logo. 
Thx.

**Comment by Aisyk** [comment]
The same case as archive.org logo, Dogmazic is a non-profit organisation.
Link for svg file : https://cloud.indie.host/s/RWnfxVuQYbtwWl2

**Comment by xuv** [comment]
Thank you.

**Comment by Aisyk** [comment]
Thanks !
