### ISSUE TITLE
 Icon request: fa-react

### ISSUE THREAD

**Issue by MrDragonXM15** [ForkAwesome/Fork-Awesome#52]
Can you make an icon for react ?
https://reactjs.org/
https://fontawesome.com/icons/react?style=brands

**Comment by xuv** [comment]
@MrDragonXM15 Sure. Though I'd be curious which use case you'd have for it? And why you'd prefer to use Fork Awesome instead of the Font Awesome 5.0 brand one which already has it?

**Comment by MrDragonXM15** [comment]
I prefer to use fork awesome because there are some icons that font awesome doesn't have. Like the icon of mastodon or the icon of discord (there is an icon of discord but I don't like it too much)

The react icon will serve me in the creation of web site
Example: Developed with `reactJSIcon` or Use `reactJSIcon`

**Comment by xuv** [comment]
@MrDragonXM15 Ok, thanks for the precisions.
