### ISSUE TITLE
Icon request: fa-hackaday

### ISSUE THREAD

**Issue by v01d** [ForkAwesome/Fork-Awesome#55]
Hi,
I would like to request a Hackaday logo to link to user profile on the site.
I've found a SVG file, but maybe it would be better to use inverted: http://hosted.hackaday.com/Hackaday_Logo.svg

Thanks

**Comment by xuv** [comment]
Hello @v01d, thanks for this suggestion. Could you provide a use case for it? Does Hackaday allows creating personal pages you want to link to? Thx.

**Comment by v01d** [comment]
Well, Hackaday allows to create projects where you write project logs. The user profile lists all the projects the user is working on. It is interesting to be able to link to your user profile and share what you do there.

**Comment by xuv** [comment]
Ok, thx for the precision.
