### ISSUE TITLE
(Icon Request) Laravel fa fa-laravel

### ISSUE THREAD

**Issue by HDVinnie** [ForkAwesome/Fork-Awesome#56]
Would be nice to add a laravel icon. What you think?

**Comment by xuv** [comment]
Hello @HDVinnie, thanks for your suggestion.
Could you provide a link to the Laravel logo (preferably in SVG) and also tell us a little bit about a use case for that icon... 
Thank you.

**Comment by HDVinnie** [comment]
I couldn't find a SVG sorry. As for use case in my projects and as seen in others sometimes there will be a "Powered By: [JS ICON], [LARAVEL ICON], [HTML5 ICON], ETC." in the site footer.

**Use Example:**
![Example](https://i.imgur.com/Vf94N5z.png)

**Icons:**
![Laravel](https://i.imgur.com/SaFjmet.png)

![Laravel](https://i.imgur.com/5Dv6mhP.png)

**Comment by xuv** [comment]
I'm getting a bit confused with all these versions of the logo... but found one in SVG in their repo...
https://github.com/laravel/art/blob/master/Laravel-l-slant.svg

So it seems to be the official one they use most of the time.

**Comment by xuv** [comment]
This is released in version 1.1.0
https://forkawesome.github.io/Fork-Awesome/icon/laravel/
