### ISSUE TITLE
Icon request: fa-nextcloud

### ISSUE THREAD

**Issue by schiessle** [ForkAwesome/Fork-Awesome#57]
It would be really nice to have a Nextcloud icon.

Here you can find various svg graphics, e.g. https://github.com/nextcloud/server/blob/master/core/img/favicon.svg

If you need another source let me know and I will provide it.

Thanks!

**Comment by tessus** [comment]
@schiessle I think the following one would be a better fit for a font icon (of course it would be black and not white 😉):

https://github.com/nextcloud/server/blob/master/core/img/logo.svg

What do you think?

**Comment by schiessle** [comment]
@tessus I agree, if you have to chose one, the logo.svg is the better one. But maybe it would make sense to have both? For example for Mastodon there is also the mastodon and the mastodon-square icon. But this decision is up to you. :slightly_smiling_face:

**Comment by schiessle** [comment]
Great, thanks a lot!

**Comment by tessus** [comment]
Status update:

I used the icons [favicon.svg](https://github.com/nextcloud/server/blob/master/core/img/favicon.svg) and [logo.svg](https://github.com/nextcloud/server/blob/master/core/img/logo.svg), adjusted the color and size, but they don't look very nice in the font. I might have to tweak the svgs or maybe even draw them from scatch.

Don't worry, `fa-nextcloud` and `fa-nextcloud-square` will be available in the next version and they will look awesome.

**Comment by tessus** [comment]
I've been able to tweak the icons and they now look great in the font.

**Comment by tessus** [comment]
@schiessle 
released in version 1.1.0
https://forkawesome.github.io/Fork-Awesome/icon/nextcloud/
https://forkawesome.github.io/Fork-Awesome/icon/nextcloud-square/
