### ISSUE TITLE
Icons only render as blocks

### ISSUE THREAD

**Issue by Sciss** [ForkAwesome/Fork-Awesome#59]
I have tried both to copy css and fonts to my project and to use the cdn rel link. In both cases I'm just seeing blocks:

![screenshot from 2018-03-26 01-17-03](https://user-images.githubusercontent.com/131300/37881321-832142c2-3096-11e8-9535-ba5d76df0d56.png)

wheres linking to the non-forked version like this worked:

    <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>

Here is the example (use view-source to check): https://www.sciss.de/ - I can't spot anything wrong. Thank you!

**Comment by Sciss** [comment]
This was caused by using css classes `fab` and `fas` instead of `fa` apparently. No idea why

**Comment by xuv** [comment]
@Sciss `fas` is the new CSS class introduced by Fork Awesome 5.0. Since we have forked it from 4.7, we are not using that nw class.

**Comment by Sciss** [comment]
Yes, sorry, I noticed that, I use `fa` now. Anyway, thanks for this lovely project

**Comment by xuv** [comment]
You're welcome. Thanks for using and promoting it.
