### ISSUE TITLE
Remove imaginary brands

### ISSUE THREAD

**Issue by xuv** [ForkAwesome/Fork-Awesome#6]
Icons to remove from the set (and save some room for more useful ones):

 - [x] https://forkawesome.github.io/Fork-Awesome/icon/pied-piper/
 - [x] https://forkawesome.github.io/Fork-Awesome/icon/pied-piper-alt/
 - [x] https://forkawesome.github.io/Fork-Awesome/icon/pied-piper-pp/

**Comment by tintincastro** [comment]
BTW, you should remove it from the documentation altogether
(From the Accessibility section @ https://forkaweso.me/Fork-Awesome/accessibility/)

```
<h1 class="logo">
  <i class="fa fa-pied-piper" aria-hidden="true"></i>
  Pied Piper, A Middle-Out Compression Solution Making Data Storage Problems Smaller
</h1>

**Comment by xuv** [comment]
Thanks for this. It's been removed from the code. Will be changed at the next deployment.

@all-contributors please add @tintincastro  for doc
