### ISSUE TITLE
Icon request : fa-jirafeau

### ISSUE THREAD

**Issue by StefOfficiel** [ForkAwesome/Fork-Awesome#61]
Hi! I think it would be nice to have a Jirafeau's icons.

Official Jirafeau's icon : 
[](https://gitlab.com/mojo42/Jirafeau/blob/master/media/courgette/logo-jirafeau.svg)

But, I think need with "Jirafeau" text and without. What are you think?

Thanks!

**Comment by StefOfficiel** [comment]
Oops, the link's gone!

[https://gitlab.com/mojo42/Jirafeau/blob/master/media/courgette/logo-jirafeau.svg](https://gitlab.com/mojo42/Jirafeau/blob/master/media/courgette/logo-jirafeau.svg)

**Comment by xuv** [comment]
Sure. Could you please provide a concrete use case? How would you use that icon and how would other people use it? Thx.
