### ISSUE TITLE
Ask CDNJS for adding

### ISSUE THREAD

**Issue by SISheogorath** [ForkAwesome/Fork-Awesome#64]
We would like to use fork-awesome in [HackMD](https://github.com/hackmdio/hackmd). But we don't like to add another external CDN provider as we try to keep external dependencies tight.

CDNJS requires the authors of the library to [ask for adding](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist).

Would be nice if someone could file an issue or a PR over there :)

**Comment by xuv** [comment]
Hey. 
Thanks for the idea. And would love to help you add it to HackMD.

This project is run by a community. So the author is the community. :)
If I add you as a collaborator, then you'll officially be part of the community and thus make the request to CDNjs.

Would that work for you? Would you like to do this request to CDNjs for the community?

Thx.

**Comment by PeterDaveHello** [comment]
Add here: 
 - https://github.com/cdnjs/cdnjs/commit/d4f2c99de3858ffa6d0eda2155e415bf210dc6de
 - https://cdnjs.com/libraries/fork-awesome

@SISheogorath I think everyone can send a request, and as you're a developer I think you can also directly send us a pull request to host this library next time, will this make sense to you?

@xuv would you like to have a CDNJS badge at the README.md? I'd like to send a pull request if you want ;)

**Comment by xuv** [comment]
@PeterDaveHello Oh, thanks for this. And yes, please add the badge to the README.
@SISheogorath Let us know when you add Fork Awesome to HackMD ;)

**Comment by SISheogorath** [comment]
It took a  while but now there is [the PR for CodiMD (former HackMD CE)](https://github.com/hackmdio/codimd/pull/993)! :tada:

**Comment by xuv** [comment]
@SISheogorath Oh, that's great news. I hope the PR will be merged soon. And thanks for keeping us updated with this.

**Comment by SISheogorath** [comment]
It's merged into master and will be published with release 1.3.0. Extended support to make things available is also on its way https://github.com/hackmdio/codimd/pull/1003.

If you want to try: https://demo.codimd.org runs the latest master

**Comment by xuv** [comment]
Great. Thanks for letting us know.
