### ISSUE TITLE
Icon request: fa-signal

### ISSUE THREAD

**Issue by qwertygc** [ForkAwesome/Fork-Awesome#65]
I suggest  a brand icon : [Signal](https://en.wikipedia.org/wiki/Signal_%28software%29) an encrypted communications app.

We have FB Messenger, WhatsApp, Telegram. Why not Signal ? it's more and more used.

The icon : https://avatars1.githubusercontent.com/u/702459?s=200&v=4

**Comment by xuv** [comment]
@qwertygc Good point.

**Comment by qwertygc** [comment]
I have tried to create the icon.

`<svg xmlns="http://www.w3.org/2000/svg" width="1536" height="1792" viewBox="0 0 1536 1792"><g transform="translate(0 739.63786)"><image y="26.8" x="214.5" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI WXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgeACoHYHVQYQAACj9JREFUaN7tWWl0U2Uafr57k3RJ 0y2hK1RKWmxZqiiLuIuIgjpqWTsgoiIqo2gRhIMDFFAEBGRREOgg+5qCC0ORRWSrYKFFp6xpKbSk pU2T5iZt0uQurz8AD+PMSAstdc7hOef+uev33Pd73ud9vw+4jdu4jT8Ca4yXmMwu9EvU/f5cOAA1 AA4AybIiDkwKsZnMLtYvUUd/9OyNgGukH6IymV3dTGbXvplbTkYBAAgFRFRCRMVEOO/1+PZduber yewik9mVaTK7womIA4AY46SbG8DNRAGAFsA/ATysKOQtKri4aO2cbAKAcycssWfyz+PYD6cpRK+F sUNLBgDz31uf26ZDbMr9fe6aqI8MsTHG8On2wtbpfRIu3NK5eIUAAGDLOXeLhbuLtz6RtqI18OLv ojuLIXoeQ+TfmCF0JNOHjmZ+huEM8TMYMIYBwNjPc/gxn+XEP5G2QgMAm886MwBg7S+2pteIyewa zDi2xny8NHV83+St/341nekjeGarnE0A6L99LyB8LB8cpiNFEiFKdeSwlBMQiuyKef6CraZEpeLU ok+60y9AU5FqDGqaKJjMrvWbzzrpjY/29P7toiad6WLHMwCYPW9PQHW1MMXpdOUJgrNEEJw2QRBc giA4BUGoFAThnMPhPFBWZhtx+eEUdXSbDHVkfAbfsu0EDgBWHqscbTK7aOMpx4tNNaV2rj5eVdqj //I7AIBHf7Tr+gkDgCqbY4AgOAsEQaD6Hk6nk+x2x8Eduwo6Ah00Le+crImM/4AHgBVHK7os2nvh myaZWusL7O0+/8BkPfj1CCuQCmALSi9ak4J1flsASr7h/M8YfD45O7nz3DQG8vFgUvn5AgnYSlmF NX6KoqT1bxu84qaJmMyuOXW13j1D7jZsB4DBI7/F2kXPwuFwTuA4+oio0YLuy82z9Or52LTcmIRE SXSTtHDX6CRezZ+wWqo7MsYK3nw0ruE+YjK7YDK7jIyx0dtWHSgHgMf+uvsKCWElY41KAgA03Tq3 /OFY3vTnygpPqnk/Xj2ofdhJWVQGRrQMz/sjEv+TyDVue+L4wTNjN8x9IR+Yj73resLhEJYwhqFN oUNFIbRN1K87mDP9ScFRq4lqk+E3qH3oJiI6ufp41aYGE+mXqIPJ7Bogy4R/TP1qweWz78BuF4Yx hhFN6VOKQkjpEJX11uvdY1Sc4tfqzimaaqvzUZ7nOt2QRlYcrei5Y00Ot2HeCztV4RlMsmeQ0yko RI1Tn10PoqgUGAx9H4oxPiDV1tZ5hUufiA0mYjK7uH6JOuXa+wRBMOFyuro11SwDCk5UvtZ38Oqv iKPaoWP/Ql17JBVYLdVJbz4aJ9VX7JuXHrLMBACmGcuuuPQLt7IUIgISE/TvlZ87x4iY+vvNhxUA xoLDRe3rpRGT2cUBSM2csnUVAIRHBDObrXp0Y5X8DYGfnyoJXKg/R9CcyS/hFIUWpTyYOLm+Yg8k ArwesRgAbBcnKjzPDUWzgJCbm/4SY1AFajV8ndu7ODwi+Nn6EvEHSOr/Vk8PMJZdUVJks9AgICYq uCfA1JyaU639ZLuZ4znVuCVH/K7bj0g+CZIol2evzSEEahjcAANCmquFVau5aEHwsODgAO5fR4rQ 1zgmAMj3XpfIoPZhVQAu22ir0YD78vuarRdnTF3r9rGQEH9erVGzDadmdAgJ1+b1jlQr1xN7gMns GgIAke6KqyGWm4sIESlqDc8RgbWIDuVUaj73l5zCwPpoJISIVg4Zt+2aLEWe5iIiSoo7NMSfAwBJ vvw/y4ut9fIREWBK25RWqPA3XCkb4GieaQWUlQvH1CqOAKJh45+JJoUwb3S6rz5EfABUHreXoSYW uqhxKp8oFzfXatWipYc3AIwknyJHtW4x0mF1/QAcU+pDxMMYsHvTkTAICrSBAVRcbFvG2K2n4fb4 rF8uyT4LQGIqKLVOz/4jOwtm1stH+iXqpEsX7GmWIqsMjCeJFHS/r+16UVQ8tzhb4fSZSlNsQoIa gKjRaKRXuz3/beYUy3cNKRoBQNU3IUgyRI3jfOBVPx8ZtUofFjjwlkXDLTqio4ffG21MIZe91pF5 aOJESZQSh9xlqLezX/UN34JdxVp7lUTaQE5p0zr6FUlSbkka5jmGzJW5Y2KMKSoG1A16p1eASs2n Z7y09P2GNlYiER3VhQQuInkuEeNI3+oD+aejpSM5jjX5lMr5qWTZ3AX7DwKsrqzIXNtrUPcFdbXe U4XHJ5xqcM+uyMqDweHaoQt3ndMH6SMUjb9G6f3ktNWnz1QuZk2kfMYY8o5bTM8NWPlpQIBaFEXR s3jfrC6MIfXtp2b1vKFF7IHJoT5ZVqZF3dGifPBbD6gkL+TYhGSlS+eM8Xn5lvmNHRme57B3X+EX T/f9cnJYiL8PDO46t+SxlTt+LjhSlFZ9aVbZTS0HTcjM7Tl9+KQ9QDbFt5/G+7w+jaXwI2Ypq/gx SKtJaRz3luXFyw6/OfXjPftb6ANFXsV7Hh/QlfUe/MD7A5ND3gWAyPiJqCiedmOr8THGSZg+vMtu k9kVR8DGiotVj89P3+ADFAaCGcANE+E4Bp9PkvYfKv6i/4vrlhvCA2sMBq0PBM/gMb11XXq0z6+8 aP8eAHj9TFQUj2uclcaNpxzbRZ8cMeQufWcAXOnFijnBOv93fz84q7WmNCjIzxAYqAm42hz99iki VAt11rJyZ/6xfMvOkSMyv2sRF1enUqtkBvKWFZXVZv449fHwiOCsUnPF0neeMr7+WNoK7F0/7Lrj q9f+yKjZ+zAwObRPVmENPfx8Zuj+r8Y6ZZlKr62J3G7RuS379JzhLy/fCNQwQ6uEsIH97m4ZGREU LCtEZrPVtm7FvhLAW6MJjZYMei2LaRMvARDLiiweMLX4SOp9pAvTZuUfOPvGtGH3LGnX/cN6kWjw tkJWYU1+tdW5bESvGV+Yfx7fz6DXbiQinDxVuen+7hlTY4wJEkA+gIkEKOw3mgQiMMaBQFAAUrx1 smSzZHsmr1oem3Rv61fcNXVHX+0+cyuUeUp9NHFDEbnq9pIof2YptnoU1wKlyjbqglrFH4uLm/RS jDHSE9MmgcqKyt1vTB8UduCbvOrqyhqp7EKlAtl6JTm6ARQpka37qqLiDEifm9YjKHh8BoF18rp9 BTvWHNp+lQSABpFocESu6SNZeKxRZRdqNdEROq2sEBs27pmYzj2SMxlj9/i8km1wx3DDhpPVgzgV /zS7XCnEMI7rtmNNjtEQG2a956G2F0qLKle/9/TLM4CDtpvNfA3eQ8wqdG1z2t2bX+769urW7TpK 589UurJOT3crConlJVUbRj2R0RuolZJ6nYTok+32EnutopBY5/aeqii1fbpy1rc1onuhF0AUAETF T8Kl4oONUPA3ECaza6LX43vQX+uXL3qlTkNTJvZ57cPUkOUff+0JCJTr7B6Z4FiEPzVMZhc2n3Um ZBW6aFWe9cQjqcs6AToAf2fAFPzfYfa2s7r/jOZI3MZt3MafF78CKrUB0XJss0oAAAAASUVORK5C YII= " preserveAspectRatio="none" height="62.5" width="62.5"/><path d="M70.8 899.8C54.6 891.2 34.3 870.9 25.7 854.7 10.8 827 9.9 787.5 10 144.3c0-659.9 0.6-681.9 16.8-708.6 38.1-62.5-11.9-58.4 736.9-60.9 751-2.5 710.1-5.6 752.2 57.4l19.6 29.3 0 685.1c0 671.8-0.3 685.6-17.4 713.2-36 58.2-3.4 55.8-746.9 55.8-633.5 0-672.8-0.9-700.5-15.7zM473.3 736.4c2.4-7.2-4.4-8.7-22.3-5.2-20.5 4.1-27.7 1.4-35.5-13-14.3-26.7-29.4-22.9-22.3 5.5 10 39.7 19.6 46.2 50 33.8 14.6-6 28.2-15.5 30.1-21.2zm133.1-50.3c12.8-6.5 31.2-11.8 40.9-11.8 9.7 0 17.7-3.9 17.7-8.6 0-4.7-9.2-8.6-20.5-8.6-26.2 0-100.2 32.5-100.2 44.1 0 9.8 25.5 3.6 62.1-15zM863.2 674.2c0-4.9-25.9-8.6-60.3-8.6-34.5 0-60.3 3.7-60.3 8.6 0 4.9 25.9 8.6 60.3 8.6 34.5 0 60.3-3.7 60.3-8.6zm154-35.6c38.3-15.9 58-33.3 37.8-33.3-11.9 0-101.2 35.7-109.5 43.7-14.9 14.5 26 8.5 71.7-10.4zm-455.3-50.8 75.7-43.3 62.4 9.7C866.1 580 1059.1 508.3 1162 382.6 1276.3 243 1298.3 68.6 1221.4-88.6 1184.5-163.9 1144.1-211.6 1075.2-260.7 1007-309.4 958.1-330.2 870-348 699.4-382.6 529.8-330.4 406.4-205.4 289.5-86.9 251.2 61.8 294.4 230.4c20.4 79.6 48.4 130.5 104.8 190.2 40 42.3 41.5 45.8 46.4 107.7 7 88.2 10.8 102.8 26.8 102.8 7.6 0 47.9-19.5 89.6-43.3zM367.9 574.5c-13.3-44.1-27.1-64-44.4-64-15.5 0-15.2 12.4 0.6 25.5 6.9 5.7 17.1 24.6 22.7 42 13.2 41 16.2 45.8 25.3 40.2 4.2-2.6 2.3-22.2-4.2-43.6zm817.4-36c34.4-27.8 51.4-53.9 35.1-53.9-7.9 0-89.9 72.7-89.9 79.7 0 13.1 15.9 5.6 54.8-25.9zM236.3 398.4c-26.3-44.2-45.3-64-45.3-47 0 9.2 36.8 77.6 49.6 92.1 27.6 31.4 25.1 4.3-4.2-45.1zM1319.8 379c27.7-48.3 30.8-58.2 18.1-58.2-7.4 0-61 86.1-61 98 0 18.2 20.5-0.9 42.8-39.8zM177.7 215.3c-6.7-67.1-10.1-78-21.9-70.7-15.2 9.4 2.2 124.6 18.9 124.6 5.2 0 6.4-20.7 3.1-53.9zM1387.5 175.8c4.1-29.7 4.4-55.8 0.7-58-10.5-6.5-13.9 5-20.5 69.4-7.8 76.8 9 67.1 19.7-11.4zM180.1 4.1c10.6-62 1.4-92-13.5-43.9-17.6 56.5-21.3 102.1-8.4 102.1 8 0 15.2-19.2 21.9-58.2zM1389 23c0-21.6-18.9-93.6-26.9-102.4-15.1-16.6-15.8 2.7-2.1 58.3 13 52.5 28.9 76.8 28.9 44zM254.7-187.5c27.7-43.9 33.1-68.2 12.4-55.4-13.4 8.3-58.9 82.7-58.9 96.3 0 21.4 16.2 7.1 46.5-41zm1055.4-9.5c-20.8-37-56.1-74-63.6-66.6-7.1 7.1 66.7 110.3 75.2 105 4.1-2.5-1.1-19.8-11.6-38.4zM393.4-338.3c44.5-39.2 48.9-61.5 6.9-34.8-30.8 19.5-71.4 57.3-71.4 66.3 0 15.9 24 4.1 64.5-31.5zm806 13.7c0-12-92.2-72.3-104.5-68.2-6.3 2.1 9.2 19 35.9 39.2 45.8 34.7 68.5 44.3 68.5 29zM561.5-429.7c54.1-20.4 72.5-33.8 46.4-33.8-26.3 0-95.6 25.5-107.2 39.4-14.7 17.8 3.4 16.1 60.9-5.6zm456.8 0.2c0-11-44.2-30.2-88.3-38.5-52.8-9.9-38 9.8 21.5 28.7 66 20.9 66.8 21 66.8 9.8zm-198.2-47c0-10-11.4-12.9-51-12.9-28.1 0-57.1 2.3-64.6 5.2-28.3 10.9-1.8 20.6 55.8 20.6 47.4 0 59.8-2.7 59.8-12.9z"/></g></svg>`

**Comment by qwertygc** [comment]
Think you :-)
