### ISSUE TITLE
Icon Request: icon-php

### ISSUE THREAD

**Issue by jrooster** [ForkAwesome/Fork-Awesome#69]
Hi there. A PHP icon would be very nice. Thanx a lot!

**Comment by tessus** [comment]
PHP does not really have a logo, but rather just the letters php: http://php.net/images/logos/php-logo.svg

How would you use an icon like that? e.g. I doubt that it would look very nice in the dimensions 16x16 or 32x32.

**Comment by tessus** [comment]
@xuv what do you think?

**Comment by xuv** [comment]
It seems to me the oval shape around the logo is somehow part of the "brand". https://secure.php.net/download-logos.php

Definitely would make it more recognizable to me.
I don't mind adding this to the brand logo set.

**Comment by jrooster** [comment]
Thanks a lot :-). To use the oval shape is a good idea.

**Comment by tessus** [comment]
The oval shape was part of the logo, but not anymore. If you really want to bring back the oval thing, please contact the PHP developers first.

**Comment by tessus** [comment]
Sorry, my bad. It seems that the oval shape is still a possible logo. It's just that I haven't seen the oval thing for a while. The PHP site only shows the letters (without the oval).

**Comment by tessus** [comment]
released in version 1.1.0
https://forkawesome.github.io/Fork-Awesome/icon/php/
