### ISSUE TITLE
Setting up on macOS

### ISSUE THREAD

**Issue by Mikerr1111** [ForkAwesome/Fork-Awesome#71]
In the documentation are there plans for building on macOS? I saw the setup for Ubuntu where things will work if rvm and rbenv are not used. So should another ruby version manager like [chruby](https://github.com/postmodern/chruby#readme) be used for building on a Mac.

**Comment by tessus** [comment]
What do you mean by *are there plans for building on macOS*?

I build the font on macOS. I installed ruby via MacPorts and that was it.

**Comment by Mikerr1111** [comment]
When I was reading the Readme file I wasn't sure if Mac was an option to build on.
![build](https://user-images.githubusercontent.com/18353476/38782429-1b017abe-40a8-11e8-82c3-bdd3109b6ab0.PNG)

**Comment by Mikerr1111** [comment]
I got it to work. Thank you for help. 👍

**Comment by tessus** [comment]
Hmm, maybe we can improve this part of the documentation.

When I first read the README, I just thought: _hey great, I don't need to do anything for bullet 2. Less work, yeah!_
But I can see how this might lead to a confusion.
