### ISSUE TITLE
Icon request: GnuPG

### ISSUE THREAD

**Issue by nagromc** [ForkAwesome/Fork-Awesome#72]
Would GnuPG logo be interesting in Fork-Awesome?

Use case: on a personal web page to show a public key fingerprint.
Logo: https://gnupg.org

**Comment by tessus** [comment]
I've been looking for a gpg key icon myself for quite some time. I think a key icon would yield better recognition than a lock icon. But I haven't found a nice key icon yet. Any suggestions?

But having the GnuPG icon as a brand icon might not be a bad idea. Do you know, if the project has a SVG version of the icon available?

**Comment by xuv** [comment]
@tessus there are 2 key types to choose from. They don't work for you? Can you explain why?
- https://forkawesome.github.io/Fork-Awesome/icon/key-modern/
- https://forkawesome.github.io/Fork-Awesome/icon/key/

As a general thing, the GnuPG brand is a good idea to add.

**Comment by tessus** [comment]
I've considered using `fa-key-modern` a while back, but somehow it didn't feel right. It's hard to explain.

I found an SVG version of the logo: https://commons.wikimedia.org/wiki/File:GnuPG-Logo.svg

**Comment by nagromc** [comment]
> Do you know, if the project has a SVG version of the icon available?

Sure. Here is the SVG logo from the official repo: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob_plain;f=artwork/gnupg-logo-new.svg;hb=refs/heads/master

**Comment by tessus** [comment]
released in version 1.1.0
https://forkawesome.github.io/Fork-Awesome/icon/gnupg/
