### ISSUE TITLE
Icon Request: FFmpeg fa-ffmpeg

### ISSUE THREAD

**Issue by tessus** [ForkAwesome/Fork-Awesome#74]
**Icon for FFmpeg**

![ffmpeg_icon svg](https://user-images.githubusercontent.com/223439/38902395-5592984e-426e-11e8-852c-983a1cd140a1.png)

[SVG](https://upload.wikimedia.org/wikipedia/commons/7/76/FFmpeg_icon.svg)

**Use-Case**

Can be used on web sites and in projects that use FFmpeg.

**Comment by xuv** [comment]
I did not even know FFmpeg had an icon.
