### ISSUE TITLE
Icon Request: Joplin fa-joplin

### ISSUE THREAD

**Issue by tessus** [ForkAwesome/Fork-Awesome#76]
**Icon**

<img width="105" alt="screen shot 2018-04-20 at 23 21 34" src="https://user-images.githubusercontent.com/223439/39079911-e244f4a0-44f1-11e8-90ac-b87d26583055.png">

**Use-Case**

[Joplin](https://joplin.cozic.net/) is a note taking application which can sync notes with different backends (nextcloud, dropbox, webdav, ...) and is available on desktop, mobile, and as a terminal app.
The app currently uses fontawesome. A Joplin icon in the font could be used to denote internal links to other Joplin notes.
Nextcloud devs also wrote an article about Joplin a while back and such an icon could be used within the Nextcloud web interface to indicate Joplin files (especially when someone starts to write a separate Joplin app for Nextcloud).

---

Please let me know what you think. I've already created the icon, thus if it gets accepted I can push it right away.

**Comment by xuv** [comment]
I'd say, go ahead. Yo make a convincing story for it. :)
