### ISSUE TITLE
Icon request: devto

### ISSUE THREAD

**Issue by thomasbnt** [ForkAwesome/Fork-Awesome#85]
Hi ! 
I would like add `devto` logo.

* **About dev.to**

Where programmers share ideas and help each other grow. It is an online community for sharing and discovering great ideas, having debates, and making friends. Anyone can share articles, questions, discussions, etc. as long as they have the rights to the words they are sharing. Cross-posting from your own blog is welcome. 

* **Resources**

Website : https://dev.to/
SVG file (offical) : https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg | [devto-logo.svg.zip](https://github.com/ForkAwesome/Fork-Awesome/files/2078731/devto-logo.svg.zip)

**Comment by xuv** [comment]
Thx for the suggestion. Have put this on our todo list.

**Comment by Berkmann18** [comment]
+1
