### ISSUE TITLE
Icon request: fa-baseball

### ISSUE THREAD

**Issue by iamcryptoki** [ForkAwesome/Fork-Awesome#86]
Hi,

First, thank you for your fonts. They really are awesome.

I think it would be fantastic to have an icon for "Baseball".

Example : 

![15961-baseball-ball1](https://user-images.githubusercontent.com/22425397/41218340-09430bb4-6d5b-11e8-9b91-22fe7a579417.png)

More examples [here](http://freevector.co/tag/baseball).

**Comment by tessus** [comment]
Can you please describe a use case for this icon?

**Comment by iamcryptoki** [comment]
Can you please describe a use case for the existing fa-futbol-o icon?

![soccer-icon](https://user-images.githubusercontent.com/22425397/41289252-7860fcd8-6e49-11e8-962a-052ebf6987fc.jpg)

**Comment by tessus** [comment]
see https://github.com/ForkAwesome/Fork-Awesome/issues/87#issuecomment-396568095
