### ISSUE TITLE
bell and bell-o are switched up

### ISSUE THREAD

**Issue by Xesau** [ForkAwesome/Fork-Awesome#88]
`bell` is open, while `bell-o` is closed.

**Comment by xuv** [comment]
Oh. Nicely spotted. Thanks.

**Comment by tessus** [comment]
@xuv how do you want to handle this? How long have the bell icons been in the font this way?
Imagine people are using one or the other and we switch them. All of a sudden their web sites, apps, ... look like a mess.

It's a different story, when we improve icons or replace a brand icon with a newer look, but switching icons and thus changing the unicode code points might not be such a great idea.

**Comment by xuv** [comment]
@tessus My guess is that I probably inverted it by mistake when I forked from Font Awesome. So it's probably better to restore it to its original state. I'll double check to see when the switch has happened.
