### ISSUE TITLE
Icon request: fa-wikidata

### ISSUE THREAD

**Issue by maxlath** [ForkAwesome/Fork-Awesome#89]
hello, I made a comparable request on font-awesome a while ago https://github.com/FortAwesome/Font-Awesome/issues/8414

Use case examples:
* when linking to Wikidata (ex: [top-right of this page](https://inventaire.io/entity/wd:Q443410)), having something more specific than the barcode which now displays small dots on the bottom
* people wanting to use a barcode without the small dots could cheat by using the `fa-wikidata` icon ;)

An SVG of the Wikidata logo is available [here](https://upload.wikimedia.org/wikipedia/commons/d/d2/Wikidata-logo-without-paddings.svg) ([Wikimedia Commons page](https://commons.wikimedia.org/wiki/File:Wikidata-logo-without-paddings.svg))

**Comment by tessus** [comment]
I think it's a good idea. 

@xuv what do you think? btw, what's the plan for the next release? (we can discuss this offline)
