### ISSUE TITLE
Icon request: icon-gimp

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#94]
GIMP is a graphics editor like Photoshop and PhotoFiltre but mainly for GNU/Linux distros and it would great to have a font icon so it could be used for skill lists and such.
![GIMP](https://images.ecosia.org/CPBmsAaHJXbwngmZYO1OFoJPji4=/0x390/smart/http%3A%2F%2Flogonoid.com%2Fimages%2Fgimp-logo.png)

**Comment by xuv** [comment]
Great idea, but I can't seem to find a black and white official version of this logo. Anyone?

**Comment by Berkmann18** [comment]
Here's one [b&w gimp](https://goo.gl/images/bt27EX).
