### ISSUE TITLE
Icon request: icon-assembly

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#98]
There are no icons for any assembly languages (Intel x86, AT&T, MIPS) but it would be great if FA had one for ASM x86 (Intel Assembly x86) and possibly for MIPS too.

**Comment by xuv** [comment]
That sounds cool, but probably out of scope for this project. 
Unless the Assembly community (if that exists) can agree on an icon, I don't think it's our responsibility to make that proposition. So until this is resolved elsewhere, I'm going to close this issue. Happy to re-open it someday.
